### ISSUE TITLE
[TEALIUM SWIFT BUG]: Lifecycle Reports Nonexistent Crashes

### ISSUE THREAD

**Issue by tyler8691** [Tealium/tealium-swift#103]
**Your Environment**
iOS Version(s): 12.4.1
Xcode version:  10.2
Swift version: 5
Tealium Swift library version: 1.6.7
Dependency manager: Carthage
Dependency manager version: 0.33.0

**Describe the bug**
The Tealium Lifecycle module is reporting more crashes than actually occur. Besides reporting real crashes, it also reports the user swiping away the app, and the system closing the app in the background to conserve memory for other apps. Additionally, once a crash is reported, future launches seem to always report the same crash.

We discovered this after noticing our crash rates are much higher in our Adobe dashboard (integrated through Tealium) than on our Firebase crashlytics dashboard. According to Firebase less than 0.05% of our users experience a crash, but our Tealium integration into Adobe reports 82% at last check.

The lifecycle module reports crashes to Adobe using the `CrashEvent` query parameter on the `LaunchEvent` which is automatically sent (we do not trigger this event ourselves). We ran Charles proxy to see exactly when this parameter is sent in a number of scenarios:

**Test 1**
Clean install app & launch: `CrashEvent` is not sent (expected)
Swipe away app and re-launch: `CrashEvent` is sent (not expected)
Wait for system to kill app in background and re-launch: `CrashEvent` is sent (not expected)

**Test 2**
Clean install app & launch: `CrashEvent` is not sent (expected)
Wait for system to kill app in background and re-launch: `CrashEvent` is sent (not expected)

**Test 3**
Clean install app & launch: `CrashEvent` is not sent (expected)
Trigger real crash and re-launch: `CrashEvent` is sent (expected)

**Does a workaround exist?**
No workaround has been found.

**To Reproduce**
1. Perform a clean install of an app integrated with Tealium's Lifecycle module
2. Swipe the app away to kill it
3. Re-launch the app
4. Observe that the lifecycle module sends a crash event. In our case we're looking at Adobe, but presumably it could be any integration. The `lifecycle_totalcrashcount` attribute in future payloads increments each time this test is repeated.
...

**Expected behavior**
We only expect the lifecycle module to recognize true crashes, such as the application closing itself due to an exception. When the application is closed by the user or the system, this is not a true crash.

The falsely high crash rate is causing issues with our analytics reporting around conversion rates and session counts in Adobe.

We are happy to send the Charles logs if desired.

**Comment by craigrouse** [comment]
@tyler8691 Thanks for the detailed summary of the issue. To get a true indication of crashes, we recommend using our crash reporter module. This determines the cause of crashes, in addition to recording that a crash occurred.

The logic in the lifecycle module for detecting a crash relies on receiving a launch event without a prior "sleep" (background) event. A sleep event is generated whenever the app is about to go into the background (UIApplicationWillResignActive notification), and wake/launch whenever we get a UIApplicationDidBecomeActive notification. This is the same way that Adobe Analytics captures crash data (see https://docs.adobe.com/content/help/en/mobile-services/ios/analytics-ios/crashes.html).

This is just my initial feedback. Switching to the Crash Reporter module would help in this case, but we will look at improving the standard lifecycle crash tracking functionality to reduce false positives. Tracking crashes without implementing an exception handler is always going to be an inexact science, but we will certainly look at improving it.

**Comment by tyler8691** [comment]
Thanks for the quick response! It sounds like adding the crash reporter framework should override the lifecycle crash detection to make it more accurate?

We already have crash reporting through Firebase and don't necessarily need it through Tealium. Is there any way to disable lifecycle's crash detection while still getting the other lifecycle features?

**Comment by craigrouse** [comment]
@tyler8691 It's quite easy to disable the mapping in Tealium iQ or Eventstream (depending which product you're using), which will effectively disable crash reporting from the lifecycle module. If you're unsure how to do this, please contact our support team (support @ tealium.com). I believe the crash variable may be automatically mapped, so you may need to use an extension to delete the variable if it's present. Hope this answers your question.

**Comment by tyler8691** [comment]
It does, we'll go ahead and disable the crash property via an extension. Thanks for the help!
