### ISSUE TITLE
[TEALIUM SWIFT BUG]: Swift language/projects are outdated

### ISSUE THREAD

**Issue by adamlatitude** [Tealium/tealium-swift#104]
**Your Environment**
iOS Version(s) [e.g. 12.1]: 13
Xcode version 11
Swift version 5.1
Tealium Swift library version [e.g. 1.6.7]: head

**Describe the bug**
Everything needs updating to modern Swift/project settings. In some cases this is not possible for a user on the current Xcode as only an older Xcode can interpret and convert Swift 3.0 (that's pretty old!) In another case cocoapods cannot process the podfile as it conflicts with build settings expected by current Xcode. To improve customer experience it would be good to go through every sample and all code provided with Xcode 11 updating as required.

**To Reproduce**
check out tealium-swift; attempt to build samples using cocoapods/carthage as applicable. Open workspace in Xcode 11 and build.

**Comment by craigrouse** [comment]
@adamlatitude we're currently building a new major release that will be fully Xcode 11 ready. Will reply back here once the release is out.

**Comment by craigrouse** [comment]
@adamlatitude the new sample apps are now released. Let us know if you have any issues with them. Closing this for now. Thank you.
