### ISSUE TITLE
[TEALIUM SWIFT BUG]: Unable to compile on macOS 10.15

### ISSUE THREAD

**Issue by tizaks** [Tealium/tealium-swift#105]
**Your Environment**
*Fill out as appropriate.*
iOS Version(s) [e.g. 12.1]: 13.1
Xcode version [Xcode> About Xcode e.g. 10.1 (10B61)]: 11.1 (11A1027)
Swift version [e.g. 4.2]: 5.1
Tealium Swift library version [e.g. 1.6.7]: 1.7.2
Dependency manager [None/Carthage/CocoaPods]: Carthage
Dependency manager version: 0.33.0

**Describe the bug**
After updating to macOS 10.15, the library can't be compiled. This is due to TealiumCrash's dependency on `PLCrashReporter` (whether it's Tealium's fork of PLCrashReporter, or the official repo doesn't matter), which in turn depends on protobuf. The particular version of protobuf in use can't be compiled because macOS will no longer compile 32-bit.

**Does a workaround exist?**
The possible workarounds here are:
* Force the libraries to point to a fork of PLCrashReporter that uses an appropriate version of protobuf (see https://github.com/microsoft/plcrashreporter/issues/19); or
* Remove all references to PLCrashReporter from the Tealium library before compilation.

**To Reproduce**
1. Attempt to build/compile the Tealium Library on any Mac running macOS 10.15. In this case we use Carthage.

**Expected behavior**
As an iOS Developer, I'd expect that that Tealium Library compiles without problems on the latest public macOS release.

**Comment by craigrouse** [comment]
@tizaks We just discovered this issue when we tried to do a Carthage build on Friday (we're currently preparing a new release).

We have a fix in progress and hope to have it released very soon.

**Comment by tizaks** [comment]
That's great, thank you!

**Comment by craigrouse** [comment]
@tizaks just a quick update - we do finally have a solution to this. We're currently preparing a new update. Will let you know when it's ready. Thanks for your patience.

**Comment by danielbyon** [comment]
Any update on when this will be available?

**Comment by christinasund** [comment]
@danielbyon We are preparing the release now and should be ready any day now. Thanks again, everyone, for your patience!

**Comment by christinasund** [comment]
Hi @danielbyon @tizaks We just updated the crash reporter dependency and published via a minor release. We are currently using a binary build of PLCrashReporter until a formal fix is available. We didn't update the version number, but you should be fine running `carthage update` to resolve the issue you were seeing. Let us know if you are still having trouble. Another thing to note, if you are interested: we just released a beta with some new features and major upgrades (including this fix) [1.8.0-beta1](https://github.com/Tealium/tealium-swift/releases/tag/1.8.0-beta1). Feel free to try it out and let us know what you think!

**Comment by tizaks** [comment]
Thanks! I'll close now this is resolved 😄
