### ISSUE TITLE
Compile error: Ambiguous use of 'dataTask(with:completionHandler:)'

### ISSUE THREAD

**Issue by Enricoza** [Tealium/tealium-swift#108]
**Your Environment**
Xcode version: 11.1 (11A1027)
Swift version: 4.0
Tealium Swift library version: 1.8.0-beta1 

**Describe the bug**
Can't compile my project due to ambiguity between `URLSessionProtocol` methods and the methods of `URLSession`.

**Does a workaround exist?**
Yes, if I manually define the type returned from the method like so:

```
let task : URLSessionDataTask = URLSession.shared.dataTask(with: url) { (data, response, error) in {

}
task.resume()
```

**To Reproduce**
Just try to call this within your SDK or inside the sample app to get the error:

```
URLSession.shared.dataTask(with: url) { (data, response, error) in {

}.resume()
```

**Expected behavior**
It should not force me to define the type for the data task to use the system default one.

**Comment by craigrouse** [comment]
@Enricoza thanks for this. Working on a fix.

**Comment by craigrouse** [comment]
@Enricoza fix completed. Beta2 release in progress. Will post back once it's up.

**Comment by craigrouse** [comment]
@Enricoza this should now be resolved in beta2. Please test and let me know. Thank you. https://github.com/Tealium/tealium-swift/releases/tag/1.8.0-beta2

**Comment by Enricoza** [comment]
@craigrouse thanks for the fix, now it's working correctly.
