### ISSUE TITLE
[TEALIUM SWIFT BUG]: TealiumFileStorage requires signing from unknown team when used as a Git submodule

### ISSUE THREAD

**Issue by Ferdzz** [Tealium/tealium-swift#110]
**Your Environment**
iOS Version(s): 13.0
Xcode version: 11.0 (11A420a)
Swift version: 4.2
Tealium Swift library version: 1.7.3 (d521b479983f7bf1759bd4df73faf202c7443500)
Dependency manager: None (Git submodules)

**Describe the bug**
When included as Frameworks, some of the components of the project tealium-swift have code signing enabled for an unknown team. This is a problem, because the build machine cannot sign the Frameworks according to their configuration. This is only a problem on `TealiumFileStorage` as well as `TealiumLifecycle`. All other Frameworks have signing disabled. 

I believe this may be a simple mistake, and that the singing can be removed from these Frameworks

**Screenshots**
TealiumFileStorage signing tab (this is a problem):
![image](https://user-images.githubusercontent.com/7923672/68223000-fb338100-ffb9-11e9-9f6a-df7c0b515f86.png)
TealiumDataSource signing tab (this works fine): 
![image](https://user-images.githubusercontent.com/7923672/68223087-21592100-ffba-11e9-8925-a52b4cea6bad.png)

**Additional context**
I'd be more than happy to open a PR to fix this, if all that's required is to remove the code signing to match every other Frameworks. Please let me know if I can go ahead and do that!

**Comment by craigrouse** [comment]
Sorry about that @Ferdzz. Hang tight and we'll fix it up and re-release ASAP.

FYI, we also have a beta available for the next release here: https://github.com/Tealium/tealium-swift/releases/tag/1.8.0-beta2. The file storage module is no longer required in the beta, as persistent storage is integrated into the Core module.

**Comment by craigrouse** [comment]
@Ferdzz I have just pushed a fix for this. Please make sure when you download that your 1.7.3 release is pointing to commit  `faabf20`.

**Comment by Ferdzz** [comment]
Thank you for your very quick response. Updated, throwing it on the CI to see if it works

**Comment by Ferdzz** [comment]
It's working! Thanks again for your quick help :)

**Comment by craigrouse** [comment]
Great to hear. Thanks for taking the time to report it @Ferdzz.
