### ISSUE TITLE
WKHTTPCookieStoreObserver stops working when using tealium-swift 1.7.1 with WKWebView

### ISSUE THREAD

**Issue by Hartmut-Lege** [Tealium/tealium-swift#117]
What we do in our app:
`WKWebsiteDataStore.default().httpCookieStore.add(ourWKHTTPCookieStoreObserver)`

We initialize our own WKWebView like this:
```
        let config = WKWebViewConfiguration()
        config.websiteDataStore = WKWebsiteDataStore.default()
        config.processPool = WKProcessPool()
        let wv = WKWebView(frame: .zero, configuration: config)
```

When a cookie is set in our WKWebView, _cookiesDidChange(in:)_ of our observer used to be called.

Now, with tealium-swift 1.7.1 and WKWebView, _cookiesDidChange(in:)_ has stopped being called.
Our current workaround is to use _TealiumConfig#setShouldUseLegacyWebview(shouldUse: true)_.
But UIWebview is deprecated and we would prefer to get rid of this legacy solution.

**Comment by craigrouse** [comment]
@Hartmut-Lege Thanks for reporting this. I'm looking into this as a top priority.

**Comment by craigrouse** [comment]
@Hartmut-Lege could you post your `cookiesDidChange` block? Thanks.

**Comment by Hartmut-Lege** [comment]
What we do in _cookiesDidChange_ is:
```
func cookiesDidChange(in cookieStore: WKHTTPCookieStore) {
    DispatchQueue.main.async {
        cookieStore.getAllCookies { cookies in
            CookieHandling.logCookies(cookies, sourceIdentifier: "WkWebsiteDataStore")
            self.wkCookiesChanged(cookies)
        }
    }
}

func wkCookiesChanged(_ changedCookies:[HTTPCookie]) {
    self.cookies = changedCookies
    if let tokenCookie = changedCookies.filter({ $0.name == "Our Cookie Name" }).first {
        self.myToken = tokenCookie.value.count == 0 ? nil : tokenCookie.value
    }
}
```

**Comment by craigrouse** [comment]
Thanks @Hartmut-Lege. Looking into this now. At first glance, I can't see why what we're doing would cause this behavior; we're simply adding an observer like you are, and retrieving the cookies. I'm guessing this may be another undocumented "feature" of WKWebView. Will get back to you ASAP.

**Comment by craigrouse** [comment]
@Hartmut-Lege I've just tested, and I'm not even seeing our own observer being called any more... seems it may be an iOS 13 bug: https://stackoverflow.com/questions/58397343/from-ios-13-0-cookiesdidchange-is-never-triggered-when-cookies-change-on-webview

If I go back to iOS 11.4, it works, but I can't even get it to trigger on iOS 12 now. Which iOS version are you testing with? Thanks.

**Comment by craigrouse** [comment]
@Hartmut-Lege I just tested again on a blank project with iOS 12.0 and iOS 13.2, without the Tealium Swift SDK.

Here's my view controller:

```
//
//  ViewController.swift
//  WebviewCookieTest
//
//  Created by Craig Rouse on 27/11/2019.
//  Copyright © 2019 Tealium. All rights reserved.
//

import UIKit
import WebKit

class ViewController: UIViewController {

    var webview: WKWebView?
    var observer = wkobserver()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.setupWebview()
        // Do any additional setup after loading the view.
    }

    func setupWebview() {
        let config = WKWebViewConfiguration()
        WKWebsiteDataStore.default().httpCookieStore.add(self.observer)
        config.websiteDataStore = WKWebsiteDataStore.default()
        config.processPool = WKProcessPool()
        self.webview = WKWebView(frame: .zero, configuration: config)
        DispatchQueue.main.async {
            self.webview?.load(URLRequest(url: URL(string: "https://tags.tiqcdn.com/utag/services-crouse/main/dev/mobile.html")!))
        }
        self.view.addSubview(self.webview!)
    }

}

class wkobserver: NSObject, WKHTTPCookieStoreObserver {
     var cookies: [HTTPCookie]?
     func cookiesDidChange(in cookieStore: WKHTTPCookieStore) {
         DispatchQueue.main.async {
             cookieStore.getAllCookies { _ in
                print("🍪🍪🍪🍪🍪Cookie monster!🧟‍♂️🍪🍪🍪🍪🍪")
             }
         }
     }
 }
```

Run this on iOS 11.4, and the cookiesDidChange method runs as expected. Run it on iOS 12+, and it never runs. Is this the behavior you're seeing?

**Comment by Hartmut-Lege** [comment]
Are you sure that it never runs? I added your example code to a ViewController of our project and it did run (also on an iPhone 11), as long as our other observer had not yet been registered. Maybe your set-up was different.

I rather assume that what causes the issue is: 2 WKWebViews (ours and the one of tealium-swift) observing both the _WKWebsiteDataStore.default().httpCookieStore_.

**Comment by craigrouse** [comment]
@Hartmut-Lege this was on a blank app using iOS 13 (or 12). Which OS version are you testing on?

**Comment by Hartmut-Lege** [comment]
I tried your example in a blank app and indeed it does not work on iOS 13. But in my opinion, this is probably due to some changes regarding cookies set by javascript code. If you replace the url of your example by one that uses "setCookie" in the http response (I tried https://www.google.com/) it works on iOS 13 too.

So I think this is not our bug. We are using "setCookie" in the http response. And we have not seen any differences related to iOS versions. This is why we rather think that there is an issue with 2 simultaneous observers, observing the same default WKWebsiteDataStore, but belonging to 2 different WKWebViews. Maybe the issue is related to the fact that WKWebView runs in its own process. This would explain why our code works fine with your UIWebvView legacy option.

**Comment by craigrouse** [comment]
@Hartmut-Lege sorry for the late reply. We'll include an option to disable the cookie observer in the next release, which should allow you to upgrade.

**Comment by craigrouse** [comment]
@Hartmut-Lege Version [1.8.2](https://github.com/Tealium/tealium-swift/releases/tag/1.8.2) is now released, which includes an option to prevent the cookie observer from being added. Please note that there's a small chance that cookies may not be synced correctly during the migration from UIWebView to WKWebView, as there's a bug in WKWebView that seems to prevent cookies from being persisted properly, unless you retrieve all cookies in the observer on the main thread once they are set. I would recommend adding this to your cookie observer if you don't already have it, in order to reduce the chances of this happening:

```
    public func cookiesDidChange(in cookieStore: WKHTTPCookieStore) {
        DispatchQueue.main.async {
            cookieStore.getAllCookies { _ in
                // no action necessary; retrieving the cookies forces them to sync
            }
        }
    }
```

If cookies are not migrated successfully, there's a chance that you may temporarily see 100% new visitors in your analytics tools until the cookies have been set for the first time. It is therefore necessary to test thoroughly. Let us know if you have any further questions about this. We'll keep the issue open until you confirm that the fix works for you. Thank you.

**Comment by Hartmut-Lege** [comment]
The update to version 1.8.2 alone did not fix our bug.
I am currently testing a workaround that consists of better controlling the initialization sequence:

1. Create my WKWebsiteDataStore instance: 
`let myWebsiteDataStore = WKWebsiteDataStore.default()`
2. Add my observer:
`myWebsiteDataStore.httpCookieStore.add(myWKHTTPCookieStoreObserver)`
3. Start Tealium: 
`let myTealiumInstance = Tealium(config: myConfig) { ... }`
4. Load my first WebView url
5. Load Tealium WebView; i.e.: I delay the call in the completion block of migrateCookies(...) so that it runs after my WebView.load(...):
```
    // TealiumTagManagementWKWebView.swift 132:
    TealiumQueues.mainQueue.asyncAfter(deadline: DispatchTime.now() + 2.0) {
        webview.load(request)
    }
```

Of course, I do not consider this as a solution to be used in production, especially not the last step. But I am pretty sure that the order of initialization has an impact. Unfortunately the bug (i.e. our login token not being stored) occurs sporadically. Thus I am not 100% sure if my workaround really fixes it, or just makes it more seldom. 

I am testing with iOS 11.4.1, 12.4.1 and 13.3. The iOS 11 device (an iPhone 5s) has the bug more frequently that the others, but they all have it.

**Comment by craigrouse** [comment]
@Hartmut-Lege Sorry this hasn't fixed the problem; WKWebView and cookies is a dark art! We also found that there are many undocumented differences and inconsistencies between iOS versions.

We do have an internal option to skip the cookie migration, which is currently not configurable. I believe if we make cookie migration optional via the TealiumConfig, it will totally solve your problem, but this will mean that we won't perform any migration from UIWebView to WKWebView. You could add this code yourself, however, if you definitely need your analytics cookies copied over. It's worth noting that we only do the migration the first time, and store a UserDefaults key to skip this step if it's already been performed (i.e. it should only happen on the first launch).

Let me know your thoughts; if making the migration optional sounds like a good option for you, we can do this quickly.

If you'd like some direct support, please get in touch with support@tealium.com, and we will gladly set up a screen sharing session to troubleshoot this with you in your app.

We appreciate your patience, and thank you for taking the time to test and troubleshoot.

**Comment by Hartmut-Lege** [comment]
Thanks @craigrouse for taking the time to support us in debugging this issue.

My lesson here is that our cookie handling needs to be made more robust towards the unavoidable interference caused by the WKWebView of Tealium. Actually the issue will be obsolete for us soon, as new requirements necessitate a complete redesign of this component. In the meantime, will keep version 1.7 and its _setShouldUseLegacyWebview_ option.

**Comment by craigrouse** [comment]
@Hartmut-Lege Thanks for your reply. Sorry we couldn't help more. It may be worth getting in touch with support and reviewing your configuration, as it may be possible to switch some of your tracking to server-side using Tealium EventStream, which may eliminate the need for the webview altogether.

**Comment by Hartmut-Lege** [comment]
To avoid confusion: Version 1.8.2, marked as fix version for this ticket, does not fix the issue we have in our app.

**Comment by craigrouse** [comment]
@Hartmut-Lege We would still be very happy to spend some time looking into this with you to come up with a solution, if that's of interest, but I understand you have a workaround for the time being. Just get in touch with our support team if you'd like to do this. Thank you.
