### ISSUE TITLE
[TEALIUM SWIFT BUG]: Tealium Swift v. 1.7.0-1.8.1 not working on Swift 5 and Xcode 11.2.1

### ISSUE THREAD

**Issue by dbacic9** [Tealium/tealium-swift#124]
iOS Versions: all
Xcode version: 11.2.1 (11B53)
Swift version: 5
Tealium Swift library version: from 1.7.0 till the latest 1.8.1 
Dependency manager: CocoaPods
Dependency manager version: 1.8.4

Tealium is not sending any reports nor is there any error in the log (I set the log to verbose). I tracked the traffic with Charles and nothing is sent on the side of Tealium.

**Workaround**
I switched to TealiumIOS and it works just fine!!!

**To Reproduce**
Just plug in the pod, initialize it and nothing happens.

**Expected behavior**
To send logs.

**Comment by craigrouse** [comment]
@dbacic9 did you disable the consent manager or set the consent status to consented? If not, then all tracking calls will be blocked until you set the consent status.

**Comment by dbacic9** [comment]
hi @craigrouse and thanks for the quick response :) we have never set the consent on v. 1.7.1 and it was working so it seems pretty strange that it stopped working by itself couple of days ago with no changes on our side..

I tried setting the consent manager to consented on Swift 1.7.1 version and it seems to work.. but then I see couple of new questions:

1. Why does it work on the objC version without setting the consent?
2. Also for Android v5.5.4 of the lib, we didn't ever set the consent and it works still?

Thanks in advance :)

**Comment by craigrouse** [comment]
@dbacic9 Apologies for the late reply. The [docs](https://docs.tealium.com/platforms/ios-swift) will be updated in the next couple of days to make it more obvious that consent manager is enabled by default for the Swift library. For iOS (ObjC) and Android, due to library architecture differences, it is disabled by default. This will be harmonized in a future release. Thank you.
