### ISSUE TITLE
[TEALIUM SWIFT BUG]: Implicit import of Bridging Header

### ISSUE THREAD

**Issue by ffittschen** [Tealium/tealium-swift#125]
## Environment
iOS Version(s) [e.g. 12.1]: 13.3
Xcode version [Xcode> About Xcode e.g. 10.1 (10B61)]: 11.3.1 (11C505)
Swift version [e.g. 4.2]: 5.1.3
Tealium Swift library version [e.g. 1.6.7]: 1.8.2
Dependency manager [None/Carthage/CocoaPods]: Carthage
Dependency manager version: 0.34.0

## Description

After upgrading to the latest release of tealium we get this warning in our project:

> warning: implicit import of bridging header 'diskstorage-Bridging-Header.h' via module 'TealiumCore' is deprecated and will be removed in a later version of Swift

This warning should be resolved, otherwise projects that use the "warnings as errors" setting in Xcode cannot be built anymore.

### Does a workaround exist?
No.

### Steps To Reproduce
1. Use the sdk version mentioned in the environment section
1. Build the app

### Expected behavior
I expect that I don't see any warnings in Xcode that originate from third-party frameworks.

### Screenshots
![Screen Shot 2020-01-21 at 17 08 35](https://user-images.githubusercontent.com/7734806/72821337-aa562f00-3c70-11ea-81ef-2c3d9724da65.png)

**Comment by craigrouse** [comment]
@ffittschen Thanks for reporting. This is resolved in a forthcoming release. Will post back here when it's out.

**Comment by ffittschen** [comment]
Perfect, thank you!

**Comment by craigrouse** [comment]
@ffittschen Tealium Swift 1.9.0 is now released, and includes a number of enhancements, including this one. Swift package manager is now also supported as an installation method. Unfortunately, there's been a slight technical issue with the documentation being published (docs.tealium.com/platforms/ios-swift), but this will be resolved later today. Please be sure to read the release notes before upgrading: https://github.com/Tealium/tealium-swift/releases/tag/1.9.0. Let us know if you have any further issues. Thank you.

**Comment by craigrouse** [comment]
Closing this issue now, as it was fixed in 1.9.0. Please re-open if you have any further issues. Thanks.
