### ISSUE TITLE
TealiumSwiftExample failed with exit code 74

### ISSUE THREAD

**Issue by vlaskos** [Tealium/tealium-swift#128]
Latest master is failing 
via carhage update

A shell task (/usr/bin/xcrun xcodebuild -project /Users/svc_jenkins_do2lapp1/workdir/workspace/CICD/IOS/Carthage/Checkouts/tealium-swift/samples/TealiumSwiftExample/TealiumSwiftExample.xcodeproj CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 74:
xcodebuild: error: Could not resolve package dependencies:
  Authentication failed because no credentials were provided.

**Comment by craigrouse** [comment]
Looking into this now @vlaskos.

**Comment by christinasund** [comment]
@vlaskos Thanks for bringing this to us. You should be able to pull the latest and run `carthage update --platform ios` `watchos` and `tvos` just fine. We are still seeing issues with `macos` and will continue troubleshooting. If you do need to build for macOS right away, we would recommend using [Swift Package Manager](https://developer.apple.com/documentation/xcode/adding_package_dependencies_to_your_app) as there are no problems there. Thanks again!

**Comment by vlaskos** [comment]
I used carthage update --no-use-binaries --platform iOS --cache-builds
version 1.8.2 works fine

**Comment by craigrouse** [comment]
@vlaskos Are you still unable to install 1.9.0? If so, then you may need to clear your Carthage cache.

**Comment by vlaskos** [comment]
I tried it yesterday few times with removing Build folder and terminal command rm -rf ~/Library/Caches/org.carthage.CarthageKit
after that I decreased version to 1.8.2 
I have not tried to update 1.9.0 again

**Comment by craigrouse** [comment]
@vlaskos please try one more time, and be sure to clear your Carthage build folder in your app's source directory.

If you are still having trouble after that, can you try changing your cartfile to `github "tealium/tealium-swift" "master"` and see if the problem goes away? Thank you.

**Comment by craigrouse** [comment]
@vlaskos we just pushed a new release to solve the Carthage issues. There are no changes apart from the version number (1.9.1). Thank you.

**Comment by craigrouse** [comment]
Further to our previous comments, this appears to be due to a [bug in Carthage](https://github.com/Carthage/Carthage/issues/2940#issuecomment-588520625) that's been open for quite some time. We are looking into possible workarounds.

**Comment by craigrouse** [comment]
@vlaskos I believe we've resolved this now - Carthage didn't like the "SDKROOT" build setting in our project. Could you please confirm if version [1.9.3](https://github.com/Tealium/tealium-swift/releases/tag/1.9.3) resolves your issue? Thanks.

**Comment by vlaskos** [comment]
1.9.1 version works fine

but we have something new 
version 1.9.3 
- cache was removed by rm -rf ~/Library/Caches/org.carthage.CarthageKit and from folder Carthage/Build and Carthage/Checkouts
- carthage update --no-use-binaries --platform iOS

```
*** Building scheme "TealiumCrashReporter-iOS" in CrashReporter.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/macbook/Projects/acex.ios.aukb/Carthage/Checkouts/plcrashreporter/CrashReporter.xcodeproj -scheme TealiumCrashReporter-iOS -configuration Release -derivedDataPath /Users/macbook/Library/Caches/org.carthage.CarthageKit/DerivedData/11.1_11A1027/plcrashreporter/1.3.9 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/85/q4c0x5_91v9gr2tv2x48z_qr0000gn/T/plcrashreporter SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/macbook/Projects/acex.ios.aukb/Carthage/Checkouts/plcrashreporter)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/85/q4c0x5_91v9gr2tv2x48z_qr0000gn/T/carthage-xcodebuild.Sp10yO.log*** Building scheme "TealiumCrashReporter-iOS" in CrashReporter.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/macbook/Projects/acex.ios.aukb/Carthage/Checkouts/plcrashreporter/CrashReporter.xcodeproj -scheme TealiumCrashReporter-iOS -configuration Release -derivedDataPath /Users/macbook/Library/Caches/org.carthage.CarthageKit/DerivedData/11.1_11A1027/plcrashreporter/1.3.9 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/85/q4c0x5_91v9gr2tv2x48z_qr0000gn/T/plcrashreporter SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/macbook/Projects/acex.ios.aukb/Carthage/Checkouts/plcrashreporter)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/85/q4c0x5_91v9gr2tv2x48z_qr0000gn/T/carthage-xcodebuild.Sp10yO.log
```

**Comment by craigrouse** [comment]
@vlaskos that is strange. We'll take a look.

**Comment by craigrouse** [comment]
@vlaskos just wanted to check - is this on your local machine, or on a CICD server? Are you able to try this on a different machine at all? Could you try also changing your Cartfile temporarily to just include `github tealium/plcrashreporter`? I'm not able to reproduce that error on my machine, whatever I try. Thanks, and sorry for the inconvenience this is causing you.

**Comment by ffittschen** [comment]
Just to chime in, since we have a very similar problem:

I just added solely github "tealium/plcrashreporter" into a Cartfile and executed the update command afterwards:

```
carthage update plcrashreporter --platform ios
*** Fetching plcrashreporter
*** Checking out plcrashreporter at "1.3.9"
*** xcodebuild output can be found in /var/folders/m2/8kggf73s7tdc3c14z5btfx5w0000gn/T/carthage-xcodebuild.gV3Cye.log
*** Building scheme "TealiumCrashReporter-iOS" in CrashReporter.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/ffittschen/Downloads/Tealium_AppCenter/Carthage/Checkouts/plcrashreporter/CrashReporter.xcodeproj -scheme TealiumCrashReporter-iOS -configuration Release -derivedDataPath /Users/ffittschen/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11E146/plcrashreporter/1.3.9 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/m2/8kggf73s7tdc3c14z5btfx5w0000gn/T/plcrashreporter SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/ffittschen/Downloads/Tealium_AppCenter/Carthage/Checkouts/plcrashreporter)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/m2/8kggf73s7tdc3c14z5btfx5w0000gn/T/carthage-xcodebuild.gV3Cye.log
```

The content of the build log hints that the underlying error is the following:

> /bin/sh: protoc-c: command not found
> Command RuleScriptExecution failed with a nonzero exit code

**Comment by craigrouse** [comment]
Thank you @ffittschen. That error is very helpful, and we should be able to get you a fix very soon.

**Comment by craigrouse** [comment]
@ffittschen @vlaskos Could you possibly try editing your cartfile for me, and add the branch name "1.9.4"?

`github "tealium/tealium-swift" "1.9.4"`

I was unable to reproduce your issue, running the exact same commands as you, but I believe switching to the binary dependency for the crash reporter module should solve the problem. Once you confirm it fixes your build issue, we'll publish this to master. Thanks for your patience.

**Comment by craigrouse** [comment]
@ffittschen @vlaskos  Could you possibly try editing your cartfile for me, and add the branch name "1.9.4"?

`github "tealium/tealium-swift" "1.9.4"`

I was unable to reproduce your issue, running the exact same commands as you, but I believe switching to the binary dependency for the crash reporter module should solve the problem. Once you confirm it fixes your build issue, we'll publish this to master. Thanks for your patience.

**Comment by ffittschen** [comment]
Using the binary dependency for the crash reporter works as expected 👍🏻

**Comment by craigrouse** [comment]
@ffittschen Great news - thanks for confirming. The full release is coming today.

**Comment by ffittschen** [comment]
@craigrouse Btw, would it be possible for you to check in the `Cartfile.resolved` as well? We currently face an issue with Carthage ([falsely](https://github.com/Carthage/Carthage/issues/1986)) reporting a circular dependency, which would be solved if you check in the `Cartfile.resolved`. I could verify this with my fork: https://github.com/ffittschen/tealium-swift/tree/1.9.4

**Comment by craigrouse** [comment]
Will do @ffittschen. Thanks for the suggestion.

**Comment by craigrouse** [comment]
@ffittschen @vlaskos The release is up. If you could just double-check that you don't get any issues with the final release, that would be great. All tested on our end, and builds fine with Carthage with all cache removed.

**Comment by vlaskos** [comment]
Yes, now works fine
Thanks a lot!
