### ISSUE TITLE
[TEALIUM SWIFT BUG]: Please create tag 1.9.1

### ISSUE THREAD

**Issue by danielbyon** [Tealium/tealium-swift#130]
Please tag commit `b229dc713f3a71160c2402cd41e27f390f1ba2ee` (latest on master) as `1.9.1` (or whichever next version number is appropriate), as the commit to fix the "tealium-swift-builder.git" reference was pushed *after* `1.9.0` was tagged. Carthage builds are broken on 1.9.0.

I would like to point my Cartfile as `github "tealium/tealium-swift" ~> 1.9.0` instead of `github "tealium/tealium-swift" "master"`, which is what I was told by support to use as a workaround.

**Comment by craigrouse** [comment]
@danielbyon Thanks for the suggestion. 1.9.1 now up, with no changes apart from the version number. Let us know if this resolves the issue for you. Thank you.

**Comment by danielbyon** [comment]
This works, thanks!
