### ISSUE TITLE
[TEALIUM SWIFT BUG]: Crash on removing old dispatches with default maxQueueSize

### ISSUE THREAD

**Issue by ffittschen** [Tealium/tealium-swift#132]
**Environment**
iOS Version: 13.3
Xcode version: 11.3.1 (11C505)
Swift version: 5.1.3
Tealium Swift library version: 1.9.1
Dependency manager: Carthage
Dependency manager version: 0.34.0

**Description**
After upgrading to Tealium 1.9.1 from 1.8.2, we observe the following crash immediately after the app launch: `EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)` (see screenshot below)

The problem is that the default maxQueueSize in the code path visible in the screenshot is `-1` and therefore this method tries to call `suffix(from:)` with a value that is not a valid index in the array.

**Does a workaround exist?**
Yes, for now, we changed the `dispatchQueueLimit` in the TealiumConfig to a value different than default value of `-1`.

**Expected behavior**
No crash.

**Screenshots**
![Screen Shot 2020-03-04 at 14 39 58](https://user-images.githubusercontent.com/7734806/75886659-e01e3400-5e28-11ea-85c4-c925caa23154.png)

**Comment by craigrouse** [comment]
Thank you @ffittschen. We'll get on it right away.

**Comment by craigrouse** [comment]
@ffittschen this is now fixed and released. It was fixed in 1.9.2, but after releasing, we were able to fix another issue affecting Carthage builds, so the latest build number is 1.9.3. Let us know if you have any further issues. Thanks for your patience.

**Comment by ffittschen** [comment]
Thanks for the quick turnaround! We will integrate it into our next release and let you know if we face any issues.
