### ISSUE TITLE
[TEALIUM SWIFT BUG]: TealiumCrashReporteriOS, missing required architecture armv7

### ISSUE THREAD

**Issue by matcartmill-godaddy** [Tealium/tealium-swift#136]
**Your Environment**
*Fill out as appropriate.*
iOS Version(s) [e.g. 12.1]: 12.4, 13+
Xcode version [Xcode> About Xcode e.g. 10.1 (10B61)]: Version 11.2.1 (11B500)
Swift version [e.g. 4.2]: 5
Tealium Swift library version [e.g. 1.6.7]: 1.8.2 & 1.9.3
Dependency manager [None/Carthage/CocoaPods]: Cocoapods
Dependency manager version: 1.9.0

**Describe the bug**
When archiving the app for submission to the App Store, the following error is encountered:

```
▸ Linking TealiumSwift
⚠️  ld: ignoring file /Users/me/Development/ios-myapp/Pods/TealiumCrashReporter/TealiumCrashReporteriOS.framework/TealiumCrashReporteriOS, missing required architecture armv7 in file /Users/me/Development/ios-myapp/Pods/TealiumCrashReporter/TealiumCrashReporteriOS.framework/TealiumCrashReporteriOS (2 slices)
❌  Undefined symbols for architecture armv7
> Symbol: _OBJC_CLASS_$_TEALPLCrashReportBinaryImageInfo
> Referenced from: objc-class-ref in TealiumPLCrash.o
❌  ld: symbol(s) not found for architecture armv7
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Does a workaround exist?**
No

**To Reproduce**
Steps to reproduce the behavior. If applicable, please attach sample code showing how to reproduce the bug. Remember to keep your Tealium account details private, and only post generic code. Additional code or crash logs may be shared with us privately on support@tealium.com.
1. Run `set -o pipefail && xcodebuild -workspace ./MyApp.xcworkspace -scheme MyApp -destination 'generic/platform=iOS' -archivePath /Users/me/Library/Developer/Xcode/Archives/2020-03-16/MyApp\ 2020-03-16\ 20.22.15.xcarchive archive | tee /Users/me/Library/Logs/gym/Myapp-MyApp.log | xcpretty`
...

**Expected behavior**
Not encountering the error

**Screenshots**

**Additional context**
This is happening retroactively somehow. Previous release branches from over a month ago are now unable to build either. This is happening on our Bitrise Ci machines as well as locally. I have no idea how this is possible.

We were using version 1.8.2 so I tried updating our `master` branch today to 1.9.3, and that didn't change anything.

**Comment by craigrouse** [comment]
@matcartmill-godaddy looking into this right away. Are you actually using the crash reporter module? If not, then I recommend editing your podfile to only build the pods you need, and exclude crash. Thanks.

**Comment by craigrouse** [comment]
@matcartmill-godaddy I have a fix for this, coming up very shortly. Stay tuned...

**Comment by matcartmill-godaddy** [comment]
Thanks @craigrouse. We were simply using TealiumFull (`pod 'tealium-swift'`) before, yet we're really only using `Core` at the moment. Switching to using only `Core` does fix the issue, and is probably better for us short-term instead of bringing in and compiling a bunch of stuff we're not using.

Silver linings, I guess.

Thanks for your quick work on this.

**Comment by craigrouse** [comment]
@matcartmill-godaddy I encourage you to take a look at the docs [here](https://docs.tealium.com/platforms/ios-swift/install/) with recommended podfiles, since you definitely need more than just Core, otherwise no events will be dispatched. In any case, the fix is merged and currently publishing to Cocoapods, so I'm glad you highlighted this issue for us. We have changed the project for the crash reporter framework so this issue doesn't happen again. Thanks.

**Comment by matcartmill-godaddy** [comment]
@craigrouse I did look into those docs, but the app still compiled and there were no logs from Tealium added to the console. I will review that, and will also try out the fixes.

Thanks.

**Comment by matcartmill-godaddy** [comment]
@craigrouse What are the update instructions to get the change? I removed our pod cache and rebuilt with `tealium-swift` (full), and I'm seeing this error now instead:

```
▸ Linking GTMSessionFetcher

❌  /Users/mcartmill/Development/ios-polaris/Pods/tealium-swift/tealium/crash/TealiumCrashReporter.swift:14:8: no such module 'TealiumCrashReporteriOS'

import TealiumCrashReporteriOS
```

**Comment by craigrouse** [comment]
@matcartmill-godaddy you might have just been a little too quick. Could you try again? It took a little while to publish

**Comment by craigrouse** [comment]
@matcartmill-godaddy sorry - 1 more thing having just re-read your message - you would need the TealiumLogger module in order to get anything logging to the console. I just tested again with a clean project, and `pod install --repo-update` worked for me and pulled in the newest TealiumCrashReporter dependency (1.3.8)

**Comment by matcartmill-godaddy** [comment]
Heh, gotcha. Makes sense, I guess. I can confirm that 1.3.8 of that Crash Reporter does fix the issue. The project is archiving again. It did take quite a while for it to get published, but that's okay.

Appreciate the help.

**Comment by craigrouse** [comment]
@matcartmill-godaddy Great to hear. Sorry for the inconvenience, but I'm glad we could get you up and running again. I'll close this for now.

**Comment by matcartmill-godaddy** [comment]
@craigrouse We may need to re-open this. The Archiving works, but deploying to Apple gives us the following error:

```
ERROR ITMS-90057: "The bundle 'Payload/Polaris.app/Frameworks/TealiumCrashReporteriOS.framework' is missing plist key. The Info.plist file is missing the required key: CFBundleShortVersionString. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring"
Return status of iTunes Transporter was 1: ERROR ITMS-90057: "The bundle 'Payload/Polaris.app/Frameworks/TealiumCrashReporteriOS.framework' is missing plist key. The Info.plist file is missing the required key: CFBundleShortVersionString. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring"
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
```

**Comment by craigrouse** [comment]
@matcartmill-godaddy aargh! Leave it with us - will update this and get you a fix shortly.

**Comment by craigrouse** [comment]
@matcartmill-godaddy Crash reporter dependency 1.3.9 is now up on CocoaPods with the additional Info.plist key. 🤞 this works for you. Will keep an eye out for an update from you in case it doesn't - let us know. Thanks.

**Comment by matcartmill-godaddy** [comment]
@craigrouse We are able to archive and submit to Apple now. Thanks again for your work on this.
