### ISSUE TITLE
[TEALIUM SWIFT BUG]: Some time Tealium failed to track

### ISSUE THREAD

**Issue by sivamoorthykutty** [Tealium/tealium-swift#142]
Module Responses:
1. tagmanagement: FAILED TO TRACK ⚠️
🔺 The operation couldn’t be completed. (TealiumSwift.TealiumTagManagementError error 4.)

**Comment by craigrouse** [comment]
@sivamoorthykutty this can happen while the webview is loading, but when it finishes loading, the queued events will be dispatched and you should see some successful events in the logs. Please get in touch with the support team if you need further assistance - support@tealium.com.

**Comment by sivamoorthykutty** [comment]
Thanks @craigrouse
