### ISSUE TITLE
[TEALIUM SWIFT BUG]: UIWebView found vs Apple review

### ISSUE THREAD

**Issue by JuhaO81** [Tealium/tealium-swift#143]
Hello! 

We are removing UIWebView from our app to ensure AppleStore reviews are passing also at December 2020. https://developer.apple.com/news/?id=12232019b&fbclid=IwAR3j5iHOeqx51CebD4_Xwss6VG6RJkl8ASXyh2p6Zkc_gYtV6ZmVQpaIEJk

Running ```grep -r "UIWebView" .``` in our code base results to some hits from latest Tealium library. These all seems to be comments on the code BUT Apple can be nasty sometimes at reviews and rejects the apps for smallest possible reasons. Getting reject, replying them and getting another review is few days of delays at minimum to our release process. 

**Could you please remove all mentions & usage of "UIWebView" from your code base please?**

![Screenshot 2020-06-12 at 10 09 55](https://user-images.githubusercontent.com/29195184/84475916-05c3a080-ac96-11ea-9652-7c0cae509f53.png)

**Comment by craigrouse** [comment]
@JuhaO81 Thanks for raising this. A totally valid concern, and we'll get these comments removed for the next minor release.

**Comment by craigrouse** [comment]
@JuhaO81 We have just released [1.9.5](https://github.com/Tealium/tealium-swift/releases/tag/1.9.5), which should resolve this issue for you.

**Comment by JuhaO81** [comment]
Thx! Takin 1.9.5 into use now!
