### ISSUE TITLE
[TEALIUM SWIFT BUG]: LogLevel is not respected with os_log

### ISSUE THREAD

**Issue by ffittschen** [Tealium/tealium-swift#150]
**Your Environment**
*Fill out as appropriate.*
Tealium Swift library version [e.g. 1.6.7]: 2.0.0
Dependency manager [None/Carthage/CocoaPods]: Carthage
Dependency manager version: 0.46.1+nsoperations

**Describe the bug**
Setting a `logLevel` different than `.silent` in the `TealiumConfig` has no effect on the messages being logged with `os_log`.

As you can see [here](https://github.com/Tealium/tealium-swift/blob/master/tealium/core/Logger/TealiumLogger.swift#L101), for the messages send with the `TealiumLoggerType.print` type, you check if the `LogRequest` has a `logLevel` that is higher or equal to the `logLevel` specified in the config. For the `TealiumLoggerType.os` type, there is no such check. It only checks for `.silent`. This results in all messages being logged regardless of the `logLevel` setting in the config.

**Does a workaround exist?**
No.

**To Reproduce**
1. Set the `logLevel` in the config to `.error`
2. Set the dispatchers to `[Dispatchers.Collect]`
3. Track any event
4. Observe log messages with the log level `.info` being printed by the Dispatch Manager.

**Expected behavior**
By setting the `logLevel` to `.error`, I'd expect to only see log message of that severity or a greater severity.

**Actual behavior**
Every log level except `.silent` is being printed.

**Comment by christinasund** [comment]
@ffittschen Thank you for bringing this to us and thank you for the recommended fix. I tested the solution and all works as we would expect. We will push this out with our next release.

Thanks again!

**Comment by craigrouse** [comment]
@ffittschen This is actually as designed, but unfortunately `os_log` isn't properly supported by Xcode yet, and there's no way to filter logs based on the log level. os_log is designed to be used with the Console app, where you can filter out "debug" and "info" messages and just show errors. Hopefully Apple will add this in a future Xcode release. See here for more info: https://developer.apple.com/forums/thread/113073.

As you observed, setting the loglevel to `silent` stops logging completely, and if you find the os_log messages too intrusive, then I'd suggest switching to the `TealiumLoggerType.print` for now until Apple catches up (hopefully!).

It's worth noting you can also implement your own logger if you wish by conforming to the `TealiumLoggerProtocol`, which might be useful if you want more control over log messages than our default loggers.

Thank you for taking the time to report this, and please feel free to ask if you have any further questions. I'm going to close this issue for now.
