### ISSUE TITLE
Origin Field Removed in Swift

### ISSUE THREAD

**Issue by RGG-jayoung** [Tealium/tealium-swift#152]
We recently migrated from the Objective-c SDK to the Swift SDK. 

In the previous Objc SDK there was the field `origin: mobile` of which we had some important analytics attached to.

Was this moved to another property or module within the new Swift SDK? We cannot locate any documentation accounting for this difference and it looks like this was removed.

**Comment by jonathanswong** [comment]
Hi @RGG-jayoung , you can leverage the [Data Layer](https://docs.tealium.com/platforms/ios-swift/data-layer/) object to add values to your data layer.

Following the example here [TealiumSwiftExample](https://github.com/Tealium/tealium-swift/blob/a6684fc6d09382681b180b80bf7e81b849c82196/samples/TealiumSwiftExample/TealiumSwiftExample/TealiumHelper.swift#L86), this should work for you:

`self.tealium?.dataLayer.add(data:["origin": "mobile"], expiry: .forever)`

**Comment by RGG-jayoung** [comment]
Thank you. Will take this to the team.
