### ISSUE TITLE
[TEALIUM SWIFT BUG]: visitorId is not being populated

### ISSUE THREAD

**Issue by ffittschen** [Tealium/tealium-swift#153]
**Environment**
iOS Version: 14.0
Xcode version: 12.0 (12A7209)
Swift version: 5.3
Tealium Swift library version: 2.0.0

**Describe the bug**
Your [documentation](https://docs.tealium.com/platforms/ios-swift/identity-resolution/#visitor-id) states the following:
> The Tealium Swift library generates a randomized and unique persistent visitor ID the first time it is launched with the `visitorId` property. This value is included in each tracked event as the attribute `tealium_visitor_id`.

We observe that this is not true anymore. The `visitorId` property stays `nil` after Tealium has been initialized.

**Does a workaround exist?**
No

**To Reproduce**
This bug can be reproduced with your TealiumSwiftExample project.
1. Create a breakpoint in the [TealiumHelper.swift#86](https://github.com/Tealium/tealium-swift/blob/master/samples/TealiumSwiftExample/TealiumSwiftExample/TealiumHelper.swift#L86)
2. Launch the app
3. When hitting the breakpoint, print the `visitorId` in the console: `po tealium!.visitorId`

**Expected behavior**
We expect that the required modules of Tealium are initialized and have stored their data (e.g. the `visitorId`) in the data layer when the `TealiumEnableCompletion` block is being called. This was also the case on earlier versions of the Tealium Swift library.

**Comment by craigrouse** [comment]
Thanks for this report @ffittschen. Looking into it.

**Comment by opolstianko** [comment]
@craigrouse  Hey, Craig! Any updates?

**Comment by craigrouse** [comment]
Hey @opolstianko @ffittschen Yes, sorry for not updating you sooner. We found the issue and it is fixed in the next release that's just going through final QA now. We've added tests to prevent this issue from happening again.

If you need the visitor ID urgently, you can call the internal API method directly:

```
/// should be available in initialization completion block
        tealium?.zz_internal_modulesManager?.collectors.first {
            $0 is AppDataModule
        }?.data?[TealiumKey.visitorId] as? String
```

Let me know if you need any further assistance.

**Comment by ffittschen** [comment]
I can confirm that `2.1.0` of the Tealium Swift library fixed this issue. Thanks!

**Comment by craigrouse** [comment]
Thanks for confirming @ffittschen. Apologies for the inconvenience caused.
