### ISSUE TITLE
[TEALIUM SWIFT BUG]: Unable to Install 1.9.7 (Lost version in docs?)

### ISSUE THREAD

**Issue by RGG-jayoung** [Tealium/tealium-swift#155]
**Your Environment**
macOS 10.15.7 (19H2)
iOS Version(s) [e.g. 12.1]: All versions.
Xcode version [Xcode> About Xcode e.g. 10.1 (10B61)]: Xcode 12.0.1
Swift version [e.g. 4.2]: 5.3
Tealium Swift library version [e.g. 1.6.7]: 1.9.6 ----> 1.9.7
Dependency manager [None/Carthage/CocoaPods]: Cocoapods
Dependency manager version: cocoapods-1.10.0.rc.1

**Describe the bug**
We cannot yet upgrade to 2.x versions for the Swift SDK. We do however wanted to upgrade from 1.9.6 to 1.9.7 as the latest release, primarily to incorporate the deadlock fixes. When running pod update for Tealium-swift there is an error for TealiumDeviceData. The documentation also stops at 1.9.6 so 1.9.7 remains ambiguous.

**Does a workaround exist?**
Unknown

**To Reproduce**
Steps to reproduce the behavior. If applicable, please attach sample code showing how to reproduce the bug. Remember to keep your Tealium account details private, and only post generic code. Additional code or crash logs may be shared with us privately on support@tealium.com.
1. Start with a pod file with `tealium-swift`, `1.9.6`
2. Follow docs to include module  `tealium-swift/TealiumDeviceData`
3. Install or update the pod (it should install)
4. Update the version to be `1.9.7`
5. Error: `None of your spec sources contain a spec satisfying the dependency: `tealium-swift/TealiumDeviceData`.`
...

**Expected behavior**
Pod should update to 1.9.7 without issue. The docs also do not mention 1.9.7 which is on Github, so a little confused and mysterious.
https://docs.tealium.com/platforms/ios-swift-v1/release-notes/

**Screenshots**
<img width="1270" alt="Tealium Version Discrepancy" src="https://user-images.githubusercontent.com/53495188/96147265-249ca280-0ed5-11eb-8d99-8e58ed023b47.png">

**Comment by christinasund** [comment]
@RGG-jayoung Thank you for pointing out the missed version in the release notes, we will get that resolved as soon as possible. I apologize you ran into trouble getting the latest version from Cocoapods, but we have republished the version and you should be good to go now. Let us know if that is not the case.

**Comment by RGG-jayoung** [comment]
@christinasund thank you for the quick assistance. This resolved our issue!
