### ISSUE TITLE
[TEALIUM SWIFT BUG]: DeviceData.unknown not available

### ISSUE THREAD

**Issue by tmiedema** [Tealium/tealium-swift#160]
iOS Version(s): not needed
Xcode version: 12.1
Tealium Swift library version: 2.x
Dependency manager: Cocoapods

Cocoapods file:
```
pod 'tealium-swift'
pod 'TealiumCrashModule'
```

When building the project, I'll retrieve errors that `DeviceDataValue.unknown` is not found. This happens in several places, all in the `TealiumPLCrash.swift` file. 

In the `CrashModule.swift` I'll retrieve another error; _Type CrashModule does not conform to protocol Collector._ 

The project cannot be build with the CrashModule pod implemented. When only tealium-swift is implemented it works fine.

**Comment by christinasund** [comment]
@tmiedema Thank you for letting us know about this. We will work on a fix as soon as possible.

**Comment by christinasund** [comment]
Hi @tmiedema,

We have just released a [new version ](https://github.com/Tealium/tealium-swift-crash-reporter/releases/tag/2.1.0)of the `TealiumCrashModule` and the issue should be resolved. Let us know if that is not the case.

Thanks

**Comment by tmiedema** [comment]
Hi,

The project can be build again, thanks!
