### ISSUE TITLE
[TEALIUM SWIFT BUG]: Error uploading to AppStore

### ISSUE THREAD

**Issue by emadrazo** [Tealium/tealium-swift#167]
** Environment **
iOS Version(s) [e.g. 12.1]: 14.2
Xcode version [Xcode> About Xcode e.g. 10.1 (10B61)]: 12
Swift version [e.g. 4.2]: 5
Tealium Swift library version [e.g. 1.6.7]:  2.2.0
Dependency manager [None/Carthage/CocoaPods]: carthage
Dependency manager version: 

**Description**
We have tealium integrated with carthage: github "tealium/tealium-swift" "2.2.0"
We used the carthage copy-frameworks script to include in app: TealliumCollect.framework
TealliumCore.framework
TealiumRemoteCommands.framework
TealliumTagManagement.framework

The library is working but whenever we try to upload to Apple we are getting this error:
ERROR ITMS-90685: "CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'tealium.ios.core' under the iOS application 'XXX.app'."

		ERROR ITMS-90205: "Invalid Bundle. The bundle at 'XXX.app/Frameworks/TealiumCollect.framework' contains disallowed nested bundles."

		ERROR ITMS-90206: "Invalid Bundle. The bundle at 'XXX.app/Frameworks/TealiumCollect.framework' contains disallowed file 'Frameworks'."

		ERROR ITMS-90206: "Invalid Bundle. The bundle at 'XXX.app/Frameworks/TealiumCollect.framework/Frameworks/TealiumCore.framework' contains disallowed file 'Frameworks'."

		ERROR ITMS-90206: "Invalid Bundle. The bundle at 'XXX.app/Frameworks/TealiumCore.framework' contains disallowed file 'Frameworks'."

		ERROR ITMS-90205: "Invalid Bundle. The bundle at 'XXX.app/Frameworks/TealiumRemoteCommands.framework' contains disallowed nested bundles."

		ERROR ITMS-90206: "Invalid Bundle. The bundle at 'XXX.app/Frameworks/TealiumRemoteCommands.framework' contains disallowed file 'Frameworks'."

		ERROR ITMS-90206: "Invalid Bundle. The bundle at 'XXX.app/Frameworks/TealiumRemoteCommands.framework/Frameworks/TealiumCore.framework' contains disallowed file 'Frameworks'."

		ERROR ITMS-90205: "Invalid Bundle. The bundle at 'XXX.app/Frameworks/TealiumTagManagement.framework' contains disallowed nested bundles."

		ERROR ITMS-90206: "Invalid Bundle. The bundle at 'XXX.app/Frameworks/TealiumTagManagement.framework' contains disallowed file 'Frameworks'."

		ERROR ITMS-90206: "Invalid Bundle. The bundle at 'XXX.app/Frameworks/TealiumTagManagement.framework/Frameworks/TealiumCore.framework' contains disallowed file 'Frameworks'."

**Does a workaround exist?**
no

**To Reproduce**
just add the library using carthage, set up the script, and try to upload to Appstore

**Expected behavior**
App should be uploaded successfully

**Comment by christinasund** [comment]
Hi @emadrazo, thank you for reporting this! We have a fix ready to go in our next release, which should be very soon. If you prefer not to wait, you can try and use the new `--use-xcframeworks` flag with Carthage. They just released this feature and it might resolve your issue: https://github.com/Carthage/Carthage#quick-start

**Comment by emadrazo** [comment]
Thanks for the answer, seems that the flag is not ready yet, we need to wait until the next Carthage release (https://github.com/Carthage/Carthage/issues/3102). We solved this temporarily by cloning Tealium-swift repository and removing TealiumCore from the other frameworks but it would be good to come back to your repository when ready. Do you have any deadline for the next release? Thanks!

**Comment by christinasund** [comment]
@emadrazo Yes, I noticed that too. Strange that it would be in the README but not part of an official release. If you _did_ want to use the flag now, it works when Carthage is installed from source. In any case, we just released the fix for this in version [2.2.1](https://github.com/Tealium/tealium-swift/releases/tag/2.2.1) 🙂 Let us know how it goes!

**Comment by emadrazo** [comment]
Thanks for the answer, seems that the flag is not ready yet, we need to wait until the next Carthage release (https://github.com/Carthage/Carthage/issues/3102). We solved this temporarily by cloning Tealium-swift repository and removing TealiumCore from the other frameworks but it would be good to come back to your repository when ready. Do you have any deadline for the next release? Thanks!

**Comment by sgrgrsn** [comment]
Hey @christinasund!

We are experiencing this issue even when using the --use-xcframework flag on Carthage. Is there some known workaround we can use to get the app shipped?

**Comment by craigrouse** [comment]
@sgrgrsn As far as we are aware, this should work fine if you are using a recent version of Carthage. Are you getting the exact same error as the original reporter? A workaround would be to manually pull in the .xcframework files attached to the latest release, or use SPM or CocoaPods. 

Another option that might work is to try using our pre-built XCFrameworks by creating yourself a local Carthage binary specification that will avoid Carthage trying to rebuild the frameworks. To do this, create a json file at the same level as your cartfile with the following contents:

```
{
        "2.4.5": "https://github.com/Tealium/tealium-swift/releases/download/2.4.5/tealium-xcframeworks.zip"
}
```

Then change your cartfile to say:

```
binary tealium.json
```
(or whatever you call your local json file).

**Comment by craigrouse** [comment]
@sgrgrsn This thread may be useful to you also https://github.com/Carthage/Carthage/issues/2292. Do you have the Tealium frameworks embedded in another framework, or are they added directly to your app individually?

**Comment by sgrgrsn** [comment]
We added in another framework in the app, but we solved the issue by adding it via SPM instead.

**Comment by craigrouse** [comment]
@sgrgrsn Thanks for letting us know. I'm glad you were able to resolve the issue.
