### ISSUE TITLE
[TEALIUM SWIFT BUG]: Content-Length HTTP header contains wrong value

### ISSUE THREAD

**Issue by ffittschen** [Tealium/tealium-swift#176]
**Your Environment**
iOS Version(s): 14.4
Xcode version: 12.2
Swift version: 5.3.1
Tealium Swift library version: 2.1.1
Dependency manager: Carthage
Dependency manager version: 0.46.1+nsoperations

**Describe the bug**
We just discovered that the `Content-Length` header of the requests sent by the `CollectEventDispatcher` (and others?) seems to contain a wrong value. We override the collect URL and the loadbalancer cuts the content after the specified content length, which results in `invalid json payload` errors.

**Does a workaround exist?**
No.

**To Reproduce**
1. Set the collect override URL to an endpoint that uses a loadbalancer, e.g. AWS Load Balancer
2. Send some tracking events

**Expected behavior**
We expect that the HTTP payload has the length specified in the `Content-Length` header.

**Additional context**

**Comment by christinasund** [comment]
Thanks, @ffittschen,  and sorry for any inconvenience this is causing you. We will look into this and get back to you shortly.

**Comment by craigrouse** [comment]
@ffittschen we do not explicitly set the `Content-Length` header; in fact, it's not even possible for us to set it, as it's one of the reserved fields:

https://developer.apple.com/documentation/foundation/nsurlrequest

We are, however, gzipping the requests, as our servers are set up to accept gzipped requests and decompress them before processing them. Is it possible that your AWS load balancers aren't treating the request as a gzipped request? We do set the `content-encoding` header to `gzip`. 

Let us know if this is useful.

**Comment by opolstianko** [comment]
@craigrouse 
Hey, Craig
Are you sure about Content-Encoding headers? I dont see in the requests being sent(I can be wrong)

**Comment by craigrouse** [comment]
@opolstianko here's the Content-Encoding header on a live request from the SDK:

![image](https://user-images.githubusercontent.com/4818525/107534919-31e24900-6bb8-11eb-91bd-ba7e7a9564e9.png)

And here's the line in the code where we set it:

https://github.com/Tealium/tealium-swift/blob/b8c8a64fd74a790c807c22eee4000b340f004eaf/tealium/core/utils/TealiumNetworkUtils.swift#L49

Hope this helps :-)

**Comment by craigrouse** [comment]
@ffittschen @opolstianko were you able to resolve your issue, or do you need some further support from us?

**Comment by craigrouse** [comment]
Closing this issue for now. Please feel free to get in touch if we can be of further assistance.
