### ISSUE TITLE
App and Device Information is Missing

### ISSUE THREAD

**Issue by yoojinhill** [Tealium/tealium-swift#18]
Your other library: tealium-ios includes app and device information automatically.

Are there any plans to include this information in this library? 

We can include this information ourselves, but don't understand why you wouldn't include it as it seems to be basic data.

Reference: https://community.tealiumiq.com/t5/Tealium-for-iOS/Data-Layer-for-Mobile/ta-p/16329

**Comment by jalakoo** [comment]
@yoojinhill Yes, there are plans to include it as an optional module for iOS, tvOS, and watchOS targets in an upcoming feature release.  Much of the device info available in the tealium-ios (objc) library requires a dependency on UIKit, which is not available for MacOS or Swift server implementations.
