### ISSUE TITLE
[TEALIUM SWIFT BUG]: 

### ISSUE THREAD

**Issue by emadrazo** [Tealium/tealium-swift#189]
**Your Environment**
iOS Version(s) [e.g. 12.1]: 13.6.1
Xcode version [Xcode> About Xcode e.g. 10.1 (10B61)]: Version 12.4 (12D4e)
Swift version [e.g. 4.2]: 5
Tealium Swift library version [e.g. 1.6.7]: 2.2.0

**Describe the bug**
An appCenter crash is reported by a user with iPhone XR iOS 13.6.1

    libsystem_malloc.dylib
    0x19b746000 + 115868
    libsystem_malloc.dylib
    0x19b746000 + 49248
    libsystem_malloc.dylib
    0x19b746000 + 45428
    libsystem_malloc.dylib
    0x19b746000 + 46896
    libsystem_malloc.dylib
    0x19b746000 + 63296
    libsystem_malloc.dylib
    0x19b746000 + 65792
    libobjc.A.dylib
    0x19b779000 + 101504
    CFNetwork
    0x19ece1000 + 445616
    CFNetwork
    0x19ece1000 + 2310432
    CFNetwork
    0x19ece1000 + 234224
    CFNetwork
    0x19ece1000 + 160364

...
    TealiumCollect.CollectModule.dynamicTrack(_: TealiumCore.TealiumRequest, completion: ((Swift.Result<Swift.Bool, Swift.Error>, [Swift.String : Any]?)) -> ()?) -> () __hidden#470_:53
  ...
    libdispatch.dylib
    0x19b708000 + 8500
    libdispatch.dylib
    0x19b708000 + 13740
    libdispatch.dylib
    0x19b708000 + 39524
    libdispatch.dylib
    0x19b708000 + 42136
    libdispatch.dylib
    0x19b708000 + 80476
    libsystem_pthread.dylib
    0x19b76e000 + 14104
    libsystem_pthread.dylib
    0x19b76e000 + 39368

**Does a workaround exist?**

**Expected behavior**
no crash is expected

**Comment by craigrouse** [comment]
@emadrazo Thanks for reporting this. Was the crash reported by a single user, or have you seen multiple instances of it? Are you able to reproduce it? That's a little tricky to debug on its own - do you have any more detailed crash logs you could send over by email? If so, please send to support@tealium.com. Thanks.

**Comment by craigrouse** [comment]
@emadrazo do you have any more details on this? Thank you.
