### ISSUE TITLE
Redundancy in Failed Requests

### ISSUE THREAD

**Issue by yoojinhill** [Tealium/tealium-swift#19]
If a request fails will this lib try to make the request again? 

What about when there is no network?

I saw a request fail in Charles proxy but it didn't look like it was resent.

**Comment by jalakoo** [comment]
The current swift library does not have a queuing module.  Please consider the full featured Tealium-ios library at: https://github.com/tealium/tealium-ios

**Comment by yoojinhill** [comment]
Thanks. 

The description on this lib gave me the impression it had all the capabilities of tealium-ios but only for AudienceStream and written in swift to be more efficient.

As a new and potential customer it is confusing what the appropriate lib we should be using.

It would be nice to have a technical breakdown of the differences between tealium-ios and tealium-swift.

**Comment by jalakoo** [comment]
Hi @yoojinhill, 

Thanks, a master technical breakdown document for the library version is a good idea.  

This library is in minimal use and was originally intended for clients looking for a very bare bones implementation. We've been rapidly adding modules with the intent of eventually matching or exceeding the existing objc library.  However, as you've noticed, there are still a number of items to be addressed.
