### ISSUE TITLE
"lifecycle_diddetectcrash":"true" remains in lifecycle events trough entire session

### ISSUE THREAD

**Issue by JoeCrumbs** [Tealium/tealium-swift#192]
As i understand it, the Tealium Lifecycle module detects crashes, if the sdk receives a launch/wake without a prior sleep event. In this case the sdk uses "lifecycle_diddetectcrash":"true" in the corresponding wake/launch event. While debugging our application, i'm seeing "lifecycle_diddetectcrash":"true" in every lifecycle event after a launch event with "lifecycle_diddetectcrash":"true". This will stop, when i kill the app and start a new session.

Expected behaviour:
"lifecycle_diddetectcrash":"true" is only used in the launch/wake event without a prior sleep event. Subsequent lifecycle events (launch/sleep) will not contain "lifecycle_diddetectcrash":"true".

Current behaviour:
"lifecycle_diddetectcrash":"true" is only used in the launch/wake event without a prior sleep event. Subsequent lifecycle events (launch/sleep) are containing "lifecycle_diddetectcrash":"true" until the app is killed.

Steps to reproduce:

1. Trigger a real crash & relaunch: "lifecycle_diddetectcrash":"true" is sent (expected)
2. send app to background (sleep event): "lifecycle_diddetectcrash":"true" is sent (not expected)
3. move app to foreground (wake event): "lifecycle_diddetectcrash":"true" is sent (not expected)
4. repeat with same result

Please let me know if you need further Information to look into this.
I'm also happy to provide my charles logs, if needed.

**Comment by craigrouse** [comment]
@JoeCrumbs Thanks for the bug report. We fixed this in version 2.3.0. Are you on the latest version? Thanks.

**Comment by JoeCrumbs** [comment]
@craigrouse thank you for your fast reply! We are on version 2.2.2. I did not realize version 2.3.0 addresses this issue. I will talk to my devs about upgrading!

**Comment by craigrouse** [comment]
Closing as this was solved in 2.3.0. Please re-open if you're still experiencing this issue.
