### ISSUE TITLE
[TEALIUM SWIFT BUG]: Many CoreTelephony errors in the console log when running on iOS device

### ISSUE THREAD

**Issue by memfrag** [Tealium/tealium-swift#194]
**Your Environment**
iOS Version(s): 14.5
Xcode version: 12.5 (12E262)
Swift version: 5.4
Tealium Swift library version: 2.3.1
Dependency manager: Swift Package Manager
Dependency manager version: Swift 5.4

**Describe the bug**

Every time an event is tracked the following log message appears in the console:

```
[Client] Updating selectors after delegate addition failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 91 named com.apple.commcenter.coretelephony.xpc was invalidated from this process." UserInfo={NSDebugDescription=The connection to service on pid 91 named com.apple.commcenter.coretelephony.xpc was invalidated from this process.}
```

Other relevant log messages get lost in a sea of these error log messages.

**Does a workaround exist?**

There is already a workaround in `DeviceDataCarrierInfo.swift` for when running on simulator, but the error message also appears on device.

**To Reproduce**

1. Run on device with iOS 14.5.
2. Track an event.
3. Observe the error message in the console log.

**Expected behavior**

I expected there to not be a CoreTelephony error log message when tracking events.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by memfrag** [comment]
After further investigation, I have concluded that the error message appears every time `CTTelephonyNetworkInfo()` is instantiated, which it is for every tracked event.

The documentation makes it seem like that `CTTelephoneNetworkInfo` is supposed to be a more long running object, so it's probably better to not instantiate it every time anyway.

As an experiment, I **removed** the `CTTelephonyNetworkInfo()` from the `DeviceData.carrierInfo` property getter, and replaced it with private static variable, that I then accessed from the getter:

```
extension DeviceData {
    private static let networkInfo = CTTelephonyNetworkInfo()
```

Since the object is only instantiated once, the error message only appears once.

I would like to propose that the code is modified to something similar to this experiment, where the object is not (probably) unnecessarily instantiated many times.

**Comment by memfrag** [comment]
While not strictly related to this bug report, may I also suggest replacing the following adjacent code snippet in `DeviceData.carrierInfo`:

```
// pick up the first carrier in the list
for currentCarrier in newCarrier {
    carrier = currentCarrier.value
    break
}
```

with the following:

```
carrier = newCarrier.values.first
```

It is more succinct and the intent is much clearer than a for loop for retrieving the first element, thus making the clarifying comment about picking up the first carrier unnecessary. 🙂

**Comment by craigrouse** [comment]
@memfrag thanks for the detailed investigation and suggestions - we'll get this addressed ASAP. Unfortunately as you've found, it's impossible to get rid of the error completely, but your suggestion at least limits it to once per app launch. We'll update you when we have a fix.

**Comment by memfrag** [comment]
I have verified that the multiple CoreTelephone errors no longer appear in the log console when running on device in release 2.3.2

**Comment by memfrag** [comment]
(Thanks for the fix!)
