### ISSUE TITLE
TagManagement Module

### ISSUE THREAD

**Issue by jalakoo** [Tealium/tealium-swift#20]

**Comment by jalakoo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(45) Devices: Tealium-Swift: 1.2.0 - TagManagement Module](https://trello.com/c/Yt3fX7jY/7054-45-devices-tealium-swift-1-2-0-tagmanagement-module)

**Comment by craigrouse** [comment]
Swift 1.2.0 Released
