### ISSUE TITLE
Broken link to Obj-C compatible TealiumHelper

### ISSUE THREAD

**Issue by gianlucabertani** [Tealium/tealium-swift#200]
Hello,

we're trying to upgrade our current Tealium iOS Library to Tealium Swift Library in an Objective-C project. 

Your documentation, in section [Working with Objective-C](https://docs.tealium.com/platforms/ios-swift-v1/with-objective-c/), says to create a TealiumHelper.swift file and add an intermediate helper class to make it possible to call the Swift library from Objective-C.

Unfortunately, the link to the source code of this TealiumHelper class is broken and returns 404. The link is the following:

- https://raw.githubusercontent.com/Tealium/tealium-swift/master/samples/TealiumHelper.swift

Could you please fix the link or provide an alternative source for this class? It would be really of help.
Thanks and best regards.

**Comment by craigrouse** [comment]
@gianlucabertani We've updated our docs and this file is now included there https://docs.tealium.com/platforms/ios-swift/with-objective-c/. Thanks for reporting the broken link.
