### ISSUE TITLE
Full environment path in binary

### ISSUE THREAD

**Issue by umutonat** [Tealium/tealium-swift#202]
https://github.com/Tealium/tealium-swift/blob/59ae87b800f0fe383b6957cc87f213898c59f558/tealium/core/utils/AnyCodable/AnyEncodable.swift#L170

The line above should be **Debug** only. Otherwise it reveals full path of the environment in the Released Binary

**Comment by craigrouse** [comment]
Thank you for reporting this @umutonat. Good catch - we will get this into our next release that we're preparing at the moment.

**Comment by craigrouse** [comment]
This was resolved in release 2.4.0. Thank you for bringing this to our attention.
