### ISSUE TITLE
iOS15 Crash with isLowPowerModeEnabled

### ISSUE THREAD

**Issue by pBoelck** [Tealium/tealium-swift#227]
<img width="875" alt="image" src="https://user-images.githubusercontent.com/52406129/136005663-a1dc93aa-2697-4b3c-9a5a-1243ca0eb338.png">

> **TealiumSwift SwiftPackage Version:**
> 2.4.4
> 
> **OS Version:**
> iOS 15.0
> 
> **Deployment Target:**
> iOS 11, iPhone + iPad

Suggestion to fix this problem:
https://github.com/DataDog/dd-sdk-ios/pull/613

**Comment by craigrouse** [comment]
@pBoelck There is a fix available for this in the latest release. Please upgrade, and set the config flag `config.batterySaverEnabled = false`, which will prevent Tealium from registering for the low power notification. Unfortunately this is the only solution until Apple fixes the bug in iOS 15.

**Comment by pBoelck** [comment]
Thank you for the timely response. 👍

**Comment by craigrouse** [comment]
@pBoelck You're very welcome. Please note that we've been unable to reproduce the crash in our testing, but we are confident the fix should work, as it avoids us registering for the notification at all.

**Comment by pBoelck** [comment]
@craigrouse We have been unable to reproduce the crash too.
Hopefully apple will fix the problem soon.

**Comment by pBoelck** [comment]
@craigrouse
One last question from my side.
The version 2.4.4 has the config setting config.batterySaverEnabled = false.

Is it still necessary to update to 2.4.6?

**Comment by craigrouse** [comment]
@pBoelck yes - previously we still registered for the notification even with this setting set to false. Now we only register if it's set to true, so having it set to false should prevent the crash, but only in the latest release.
