### ISSUE TITLE
[TEALIUM SWIFT BUG]: SwiftLint checks failed for force unwrapping rule, Tealium Swift v2.4.5

### ISSUE THREAD

**Issue by DenisEfremov71** [Tealium/tealium-swift#229]
**Your Environment**
*Fill out as appropriate.*
iOS Version(s) [e.g. 13.1]: 14.3
Xcode version [Xcode> About Xcode e.g. 10.1 (10B61)]: 12.4
Swift version [e.g. 4.2]: 5.4
Tealium Swift library version [e.g. 1.6.7]: 2.4.5
Dependency manager [None/Carthage/CocoaPods]: None
Dependency manager version: NA

**Describe the bug**
When building my iOS app on a simulator, I received several errors related to SwiftLint check against the "force unwrapping" rule:
"Force Unwrapping Violation: Force unwrapping should be avoided. (force_unwrapping)". The sources of the errors: 

1. /tealium-swift-main/tealium/collectors/visitorservice/VisitorServiceRetriever.swift:145:69
2. /tealium-swift-main/tealium/collectors/lifecycle/Lifecycle.swift:238:37
3. /tealium-swift-main/tealium/core/connectivity/LegacyConnectivityMonitor.swift:134:63
4. /tealium-swift-main/tealium/core/connectivity/LegacyConnectivityMonitor.swift:145:66
5. /tealium-swift-main/tealium/core/utils/Data+Gzip/Data+Gzip.swift:182:123
6. /tealium-swift-main/tealium/core/utils/Data+Gzip/Data+Gzip.swift:186:91
7. /tealium-swift-main/tealium/core/utils/Data+Gzip/Data+Gzip.swift:243:123
8. /tealium-swift-main/tealium/core/utils/Data+Gzip/Data+Gzip.swift:247:91
9. /tealium-swift-main/tealium/core/storage/Disk/Disk+InternalHelpers.swift:51:48
10. /tealium-swift-main/tealium/core/storage/Disk/Disk+InternalHelpers.swift:74:54
11. /tealium-swift-main/tealium/core/storage/Disk/Disk+InternalHelpers.swift:92:50
12. /tealium-swift-main/tealium/core/TealiumAppDelegateProxy.swift:170:74
13. /tealium-swift-main/tealium/core/publishsettings/TealiumPublishSettingsRetriever.swift:101:79
14. /tealium-swift-main/tealium/core/datalayer/Expiry.swift:26:96
15. /tealium-swift-main/tealium/core/datalayer/Expiry.swift:31:96
16. /tealium-swift-main/tealium/core/datalayer/Expiry.swift:34:96
17. /tealium-swift-main/tealium/dispatchers/remotecommands/RemoteHTTPCommand.swift:93:58
18. /tealium-swift-main/tealium/dispatchers/remotecommands/RemoteCommand.swift:80:70
19. /tealium-swift-main/tealium/dispatchers/remotecommands/RemoteCommand.swift:190:28
20. /tealium-swift-main/tealium/dispatchers/remotecommands/RemoteCommandsManager.swift:85:65

**Does a workaround exist?**
No. To avoid the problem, the source code in the 2 files specified above has to be changed by Tealium team.

**To Reproduce**
To reproduce the issue, the source code files in /tealium-swift-main/tealium/* have to be checked with SwiftLint that has:
opt_in_rules:
  - force_unwrapping

**Expected behavior**
When the SwiftLint checks are done on TealiumCore.framework/Headers, there should not be any errors.

**Screenshots**
NA

**Additional context**
NA

**Comment by Enricoza** [comment]
With the `2.5.0` release this issue should be solved, the library now should not contain any force unwrapping.
Of course, for any other specific lint rule we may still not follow, you can always exclude any Tealium files out of the lint script.

**Comment by DenisEfremov71** [comment]
Thank you, Enricoza!
