### ISSUE TITLE
[TEALIUM SWIFT BUG]: Tealium swallowing URLs opened through `application continueUserActivity`

### ISSUE THREAD

**Issue by wvteijlingen** [Tealium/tealium-swift#240]
**Your Environment**
Tealium Swift library version: 2.4.6
Dependency manager: CocoaPods
Dependency manager version: 1.11.0

**Describe the bug**
Our project uses both the Firebase and Tealium pods. When we configure a Firebase In App Message with a URL, nothing happens when the user taps the message. The expected behaviour is that the URL is opened.

**What I think is happening**

I've done a little digging and I believe the problem is because Tealium swizzles `application(_ application:, continueUserActivity:, restorationHandler:)` on the application delegate.

1. Firebase handles the tap on the in app message.
2. Firebase checks the application delegate and sees that it implements `application(_ application:, continueUserActivity:, restorationHandler:)`. Even though we don't have this method on our own app delegate, there is still an implementation because Tealium swizzled this method.
3. Firebase calls the swizzled Tealium method, passing it the URL.
4. The swizzled implementation sees that we don't have an original implementation in our own app delegate, and returns `true`. See [TealiumAppProxy.swift:253](https://github.com/Tealium/tealium-swift/blob/643f802056f0157b1dbc367ff1ad03a41033c812/tealium/core/TealiumAppDelegateProxy.swift#L253).
5. Because the method returned true, iOS considers the activity as handled, and the URL is not opened.

**Does a workaround exist?**
1. Implement `application(_ application:, continueUserActivity:, restorationHandler:)` on your app delegate.

**Expected behavior**
Tealium does not swallow URLs that are opened using `application(_ application:, continueUserActivity:, restorationHandler:)`.

**Comment by craigrouse** [comment]
@wvteijlingen Thanks for the detailed bug report. We'll look into it right away. In the meantime, you can disable swizzling by adding `TealiumAutotrackingDeepLinkEnabled = false` to your app's info.plist.

**Comment by Enricoza** [comment]
@wvteijlingen we just released version `2.5.1` of the library.
We now return false in case there is no implementation and make sure to return the underlying returned value in case it is actually implemented.

I'm closing this as we think this should be enough to solve the issue, but in case something else arises feel free to reopen.

**Comment by wvteijlingen** [comment]
Just updated to 2.5.1 and it seems to work fine now. Thanks for the quick response!
