### ISSUE TITLE
Module compiled with Swift 3.0.2 cannot be imported in Swift 3.1

### ISSUE THREAD

**Issue by boudavid** [Tealium/tealium-swift#25]
I just downloaded the new Xcode 8.3 and now I am getting the error of "Module compiled with Swift 3.0.2 cannot be imported in Swift 3.1", please look into this.

**Comment by craigrouse** [comment]
@boudavid We will look into this. However, you should be aware that the current version of the Swift library does not support Tag Management, which I expect you need. The next version will include an optional Tag Management module, and should be released soon. In the meantime, if you need to use Tag Management and you are close to releasing your app, please use the Objective-C library hosted here: http://github.com/tealium/tealium-ios

**Comment by boudavid** [comment]
I tried multiple solutions but I'm still getting the error :

- carthage update --no-use-binaries
- Updated carthage to 0.20.1
- Removed the "// Generated by Apple Swift version 3.1 ..." in Tealium-Swift.h

**Comment by craigrouse** [comment]
Thanks for confirming @boudavid. We will investigate and come back to you.

**Comment by craigrouse** [comment]
@boudavid can you please check that your Carthage version is the latest (20.1)?

**Comment by boudavid** [comment]
@craigrouse It is.

**Comment by craigrouse** [comment]
Thanks for your patience @boudavid. Just ruling out anything obvious.

**Comment by boudavid** [comment]
Thank you for your quick response. If you need me to try anything, just tell me. 🙂

**Comment by boudavid** [comment]
@craigrouse When running "carthage update tealium-swift", I get an error when building the ios scheme for Tealium :

Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project <Project path>/Carthage/Checkouts/tealium-swift/builder/tealium-swift.xcodeproj -scheme ios -configuration Release -derivedDataPath /Users/davidbou/Library/Caches/org.carthage.CarthageKit/DerivedData/tealium-swift/1.1.3 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/f0/qzhsxdh5479cl3j0zsszfwyh0000gq/T/carthage-xcodebuild.O9u7Sw.log

**Comment by craigrouse** [comment]
Thanks @boudavid. Just to confirm, you still have Xcode 8.3.1 installed?

**Comment by boudavid** [comment]
I do.

**Comment by craigrouse** [comment]
@boudavid I'm sure the answer is yes, but I'll ask anyway... have you tried manually clearing your "DerivedData" folder for the Xcode project?

**Comment by boudavid** [comment]
@craigrouse Indeed I did.

**Comment by boudavid** [comment]
Hey @craigrouse, any updates on progress ?

**Comment by jalakoo** [comment]
Hi @boudavid,
Apologies for the delay, we're looking at this now. Will post updates here by the end of the day.

**Comment by jalakoo** [comment]
@boudavid Have not yet encountered the error message you reported earlier.  To confirm, we are doing the following to test:

1) Adding a cartfile to the root directory of a test project
2) Running 'carthage update'

Were there any other log messages produced?

**Comment by jalakoo** [comment]
Confirmed same error code using matching Xcode and Carthage versions. No solution for 1.1.3 yet found.  We will be looking at the 1.2.0 branch in development next.

**Comment by jalakoo** [comment]
@boudavid Our current development build for 1.2.0 looks like it works.  Testing steps:
1. Targeted local build in cartfile: `git "file:///Users/jalakoo/jalakoo/tealium-swift" "1.2.0"`
2. From sample project's folder: `carthage update --platform iOS`
3. In sample app added framework links and run script
4. Build and run app in simulator

1.2.0 Public headers need to be updated, but otherwise the sample app test was successful.  The above steps using 1.1.3, however, did NOT pass step 2 above.  Error log suggests the frameworks won't even build, but that's not what we encounter if the frameworks are compiled directly. Uncertain what the issue is with Carthage+1.1.3.  Since 1.2.0 is due to be released within 2 weeks, we're going to direct our efforts in wrapping it up.

**Comment by boudavid** [comment]
@jalakoo Thanks for looking into it. We're going to wait for the release of 1.2.0 before updating Xcode. 😃
