### ISSUE TITLE
Version 2.7.0 is suddenly missing here.

### ISSUE THREAD

**Issue by OliverDobner-DBSystel** [Tealium/tealium-swift#276]
**Your Environment**
*Fill out as appropriate.*
iOS Version(s) [e.g. 12.1]: all
Xcode version [Xcode> About Xcode e.g. 10.1 (10B61)]: all
Swift version [e.g. 4.2]: all
Tealium Swift library version [e.g. 1.6.7]: 2.7.0
Dependency manager [None/Carthage/CocoaPods]: SPM
Dependency manager version:  all

**Describe the bug**
Other a month a ago with updated our tealium dependency to version 2.7.0. Now (without any information/note) the tag (and with that the version) is missing . The commit that was marked with the tag 2.7.0 still exists. Why did you remove the tag?

**Does a workaround exist?**
If applicable, describe the workaround here.

**To Reproduce**
Steps to reproduce the behavior. If applicable, please attach sample code showing how to reproduce the bug. Remember to keep your Tealium account details private, and only post generic code. Additional code or crash logs may be shared with us privately on support@tealium.com.
1. 
2. 
3. 
4. 
...

**Expected behavior**
Existing tags are NEVER EVER deleted.

**Comment by craigrouse** [comment]
@OliverDobner-DBSystel Thanks for raising this. I'm not sure what's happened, but I can see that release is marked as a draft. I'll find out what's going on and get it resolved.

**Comment by craigrouse** [comment]
@OliverDobner-DBSystel It looks like that release was mistakenly pointing at the branch that got merged into main rather than `main` iteself. We had deleted that branch, which caused the release to get un-published. The release is now published again and correctly pointing to the `main` branch. This shouldn't affect any package managers.

**Comment by OliverDobner-DBSystel** [comment]
Thanks for the quick response.
