### ISSUE TITLE
[TEALIUM SWIFT BUG]: 

### ISSUE THREAD

**Issue by rad-chomik** [Tealium/tealium-swift#277]
**Your Environment**
*Fill out as appropriate.*
iOS Version(s) [e.g. 12.1]: 
12.6
Xcode version [Xcode> About Xcode e.g. 10.1 (10B61)]:
14.0.1
Swift version [e.g. 4.2]:
5.7.0
Tealium Swift library version [e.g. 1.6.7]: 
2.7.0
Dependency manager [None/Carthage/CocoaPods]:
CocoaPods
Dependency manager version: 
1.11.3

**Describe the bug**

Thread 9: Fatal error: EncodingError: AnyCodable value (String, Bool) cannot be encoded, codingPath: [_JSONKey(stringValue: "FilterList", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0)]. You can only add JSON encodable values to the data layer.
 **EDIT:**
After converting still getting an error. What am I missing here?
Fatal error: EncodingError: AnyCodable value (String, Int) cannot be encoded, codingPath: [_JSONKey(stringValue: "FilterList", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0)]. You can only add JSON encodable values to the data layer.: file TealiumSwift/AnyEncodable.swift, line 108

**Does a workaround exist?**
If applicable, describe the workaround here.
I found the place where I was adding the params to the dictionary and used Int instead of Bool

**To Reproduce**
Steps to reproduce the behavior. If applicable, please attach sample code showing how to reproduce the bug. Remember to keep your Tealium account details private, and only post generic code. Additional code or crash logs may be shared with us privately on support@tealium.com.
1. 
2. 
3. 
4. 
...

**Expected behavior**
In my opinion, encoding could have the option to encode the (String: Bool) option

**Screenshots**
<img width="1018" alt="Screenshot 2022-10-06 at 8 48 27 am" src="https://user-images.githubusercontent.com/91895133/194248765-ce0654d5-8a6a-4dc3-85be-a3f70fecf42b.png">
<img width="1009" alt="Screenshot 2022-10-06 at 8 48 47 am" src="https://user-images.githubusercontent.com/91895133/194248770-e483dd77-2c9b-4281-be38-ba12decac029.png">

**Additional context**

**Comment by Enricoza** [comment]
Hi @rad-chomik, thank you for opening this.
It looks like you are passing a tuple in the key "FilterList" with a string and a boolean together.
Something like this:

```
let data = [
    "FilterList": ("someFilterKey", true)
]
```

This is not Encodable by default and i don't know if we can find a unified way to embed this in a JSON for every usecase.
And even if you replace the Bool with an Int, you should get the same error complaining about the value (String, Int) that cannot be encoded.

My suggestion would be to split this tuple in two different keys.
Something like this should work:
```
let data = [
    "FilterKey": "someFilterKey",
    "FilterValue": true
]
```

Of course, if you apply any type of change to the data layer it should be reflected on the CDP.

Let me know if you still have problems.

**Comment by rad-chomik** [comment]
Hello Enrico

I appreciate your answer and suggestion.
Now I see and understand that clearer.

Interesting is that, I have switch to Tealium-swift recently and before, in the Tealium-ios, this was sent/used this way.

Not sure if that will help.

Anyway, I am grateful for your help.


Kindest regards
Rad


From: Enricoza ***@***.***>
Date: Thursday, 6 October 2022 at 9:13 am
To: Tealium/tealium-swift ***@***.***>
Cc: Chomik, Radoslaw ***@***.***>, Mention ***@***.***>
Subject: Re: [Tealium/tealium-swift] [TEALIUM SWIFT BUG]: (Issue #277)

[External] This message has originated from outside of the AA.

Hi @rad-chomik<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frad-chomik&data=05%7C01%7Cradoslaw.chomik%40theaa.com%7Cb05091adeaf143d9bce608daa772accc%7C52da6cebc43245d89cee97902996ced9%7C0%7C0%7C638006408217220649%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Bfb3NylXmtFYAKVpeeXABskqUhxObr%2FGjJDfBU1m5rM%3D&reserved=0>, thank you for opening this.
It looks like you are passing a tuple in the key "FilterList" with a string and a boolean together.
Something like this:

let data = [

    "FilterList": ("someFilterKey", true)

]

This is not Encodable by default and i don't know if we can find a unified way to embed this in a JSON for every usecase.
And even if you replace the Bool with an Int, you should get the same error complaining about the value (String, Int) that cannot be encoded.

My suggestion would be to split this tuple in two different keys.
Something like this should work:

let data = [

    "FilterKey": "someFilterKey",

    "FilterValue": true

]

Of course, if you apply any type of change to the data layer it should be reflected on the CDP.

Let me know if you still have problems.

—
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTealium%2Ftealium-swift%2Fissues%2F277%23issuecomment-1269552961&data=05%7C01%7Cradoslaw.chomik%40theaa.com%7Cb05091adeaf143d9bce608daa772accc%7C52da6cebc43245d89cee97902996ced9%7C0%7C0%7C638006408217220649%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fl%2FvWfKrIg71QqGmy2%2FCsV5CMtbJ0Z51hWSuqTm4vBI%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAV5DKXMRWZENL2OMF6XBQFDWB2C3FANCNFSM6AAAAAAQ6KHQUY&data=05%7C01%7Cradoslaw.chomik%40theaa.com%7Cb05091adeaf143d9bce608daa772accc%7C52da6cebc43245d89cee97902996ced9%7C0%7C0%7C638006408217220649%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xR4%2Fk7a%2BwCam%2F1AZjk0N4YAH3jRiX%2FwWpepJz1NbeFs%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

The information contained in or attached to this email is intended only for the use of the individual or entity to which it is addressed. If you are not the intended recipient, you are not authorised to and must not disclose, copy, distribute or retain this message or any part of it. It may contain information which is confidential and/or covered by legal professional or other privilege (or other rules or laws with similar effect in jurisdictions outside England and Wales). AA Corporation Limited - Registered Office: Fanum House, Basing View, Basingstoke, Hampshire RG21 4EA Registered in England and Wales number: 03797747

**Comment by Enricoza** [comment]
Thank you for the kind words,

I'm not sure why it used to work on the obj-c library. 
Could also be the case that it didn't work but it was harder to spot the mistake since we added this error detection only recently.

Anyway, glad I could help.
I'm gonna close this but feel free to open any other issues in case you have problems.
