### ISSUE TITLE
[TEALIUM SWIFT BUG]: 

### ISSUE THREAD

**Issue by rad-chomik** [Tealium/tealium-swift#279]
Your Environment
Fill out as appropriate.
iOS Version(s) [e.g. 12.1]:
12.6
Xcode version [Xcode> About Xcode e.g. 10.1 (10B61)]:
14.0.1
Swift version [e.g. 4.2]:
5.7.0
Tealium Swift library version [e.g. 1.6.7]:
2.7.0
Dependency manager [None/Carthage/CocoaPods]:
CocoaPods
Dependency manager version:
1.11.3

Describe the bug
When trying to build an app I am getting the following error in Migrator.swift
Value of optional type '(any ConsentConfigurable)?' must be unwrapped to refer to member 'consentStatus' of wrapped base type 'any ConsentConfigurable'

**Does a workaround exist?**
If applicable, describe the workaround here.
I unlock that pod and added '?' do not understand why this is happening as a few line above this is unwrapped 

**To Reproduce**
Steps to reproduce the behavior. If applicable, please attach sample code showing how to reproduce the bug. Remember to keep your Tealium account details private, and only post generic code. Additional code or crash logs may be shared with us privately on support@tealium.com.
1. Switch branch
2. pod instal and update
3. clean project
4. build

**Expected behavior**

**Screenshots**
<img width="1353" alt="Screenshot 2022-10-07 at 1 05 35 pm" src="https://user-images.githubusercontent.com/91895133/194550350-66fe9653-4fcd-4e8c-885e-e54713566622.png">

**Additional context**

**Comment by craigrouse** [comment]
@rad-chomik we're taking a look at this. It appears to be an Xcode 14 issue; as you said, there is nothing obviously wrong with the code. We'll get back to you as soon as we have a fix.

**Comment by craigrouse** [comment]
@rad-chomik We believe we've found the issue. You had @Enricoza and I scratching our heads, then I remembered that the syntax here changed from Swift 4 to Swift 5, and this code compiles in Swift 5 (and 5.7), but not Swift 4. Your podfile must have a script that is setting the Swift Language Version for your pods project to Swift 4. This is the only way we were able to reproduce the issue. Let us know how you get on!

**Comment by rad-chomik** [comment]
Hi @craigrouse.
Yes, our project was set to 4.2 Swift version.
Currently checking it in 5.7.
I'll let you know before EOD (approx 3pm UK time), if all is working

**Comment by craigrouse** [comment]
No problem @rad-chomik!

**Comment by rad-chomik** [comment]
Hi @craigrouse. Unfortunately, I am unable to test this properly as in the project there are a few frameworks that are still not up to date.
Any suggestion on what could I do in this case?

**Comment by rad-chomik** [comment]
Awesome. I appreciate that @craigrouse.

**Comment by rad-chomik** [comment]
Hi @craigrouse 

I've applied the fix you suggested, see below, but still getting the same error.
Please, any other suggestions?

Code I used

DEFAULT_SWIFT_VERSION = '4.2'
POD_SWIFT_VERSION_MAP = {
  'tealium-swift' => '5.7'
}
post_install do |installer|
  
  #
  # Apply iOS Distribution to all pod Release configs
  #
  installer.pods_project.targets.each do |target|
    swift_version = POD_SWIFT_VERSION_MAP[target.name] || DEFAULT_SWIFT_VERSION
    target.build_configurations.each do |config|
      if config.name == 'Release' || config.name == 'InHouse'
        puts "Setting #{target.name} Swift version to #{swift_version}"
        config.build_settings['SWIFT_VERSION'] = swift_version #'4.2'
        config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
        config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
        config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      end
    end
  end
end

Pod instal/update output
<img width="319" alt="Screenshot 2022-10-28 at 7 52 33 am" src="https://user-images.githubusercontent.com/91895133/198523601-17ae5b0e-20d2-441f-8e71-e185db1df7d4.png">

Error
<img width="1240" alt="Screenshot 2022-10-28 at 7 59 49 am" src="https://user-images.githubusercontent.com/91895133/198523826-0eb0e672-547c-4e44-b6b2-9689df0b993f.png">
