### ISSUE TITLE
Cocoapods Support

### ISSUE THREAD

**Issue by migfabio** [Tealium/tealium-swift#28]
Hello, any news about Cocoapods support?
Thanks

Old issue: https://github.com/Tealium/tealium-swift/issues/5

**Comment by jalakoo** [comment]
@migfabio Hi, we are planning on adding Cocoapods support with the next update of the Swift library, which currently undergoing documentation review prior to release.

**Comment by migfabio** [comment]
hello, sorry to bump it up. any news?

**Comment by craigrouse** [comment]
@migfabio sorry this didn't make it into the last release. I'm actively working on it and hope to have it ready very soon. I'll keep you posted.

**Comment by craigrouse** [comment]
@migfabio I've just pushed a pod up for the Swift library (1.3.3). Would you mind testing it for me to make sure it works as expected?

You'll need to add this to your Podfile:

`pod 'tealium-swift'`

If you have any Swift 4.0 issues, add this to the end of your Podfile and try again:

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.2'
        end
    end
end
```

I'm working on a minor update that will support Swift 4.0 with backwards-compatibility, but for now, Swift 3.2 is required.

To import the module, you will need to use this import statement in your Swift files:

`import tealium_swift`

Let me know how you get on. Thank you for your continued patience on this issue.

**Comment by migfabio** [comment]
@craigrouse thanks! i will try it as soon as possible

**Comment by craigrouse** [comment]
@migfabio Here's a link to the full documentation: https://community.tealiumiq.com/t5/Tealium-for-Swift/Installing-the-Swift-Library-with-CocoaPods/ta-p/20020

I'll close this for now, but please re-open or create a new issue if you have any trouble with installation.
