### ISSUE TITLE
Tealium sending requests to "tags.tqcdn.com" after overriding the tagManagementOverrideURL and publishSettingsURL

### ISSUE THREAD

**Issue by mharidyMMS** [Tealium/tealium-swift#292]
**Your Environment**
iOS Version(s): 15* + 16.*
Xcode version: xCode 14.*
Swift version: Swift 5.5
React-native version: 0.70.5
Tealium Swift library version: 2.7.0
Dependency manager: CocoaPods
Dependency manager version: 1.11.3

**Describe the bug**
After overriding the **tagManagementOverrideURL** and **publishSettingsURL** to send all the requests and the data to our URL, we figured out that Tealium still sending at least a request to "tags.tiqcdn.com". By tracking the source of the request, we have found, that the url will defined by sessionBaseUrl in dataLayerExtention.swift (in Tealium pod).

**Does a workaround exist?**
Adding a patch to set our url instead "tags.tqcdn.com" in dataLayerExtention.swift.

**To Reproduce**
1. Set a value for config.tagManagementOverrideURL and config.publishSettingsURL.
2. Delete the mobile App from your device.
3. Re-install the app.
4. Use any tool to monitor the http requests on your device (for example [charles Proxy](https://www.charlesproxy.com/)  )
5. You will find that Tealium sends a request to "tags.tqcdn.com" on starting the application.

**Expected behavior**
- Tealium will send all his requests to our url which has been set by overriding tagManagementOverrideURL and publishSettingsURL. And no requests will be sent to "tags.tiqcdn.com".

**Screenshots**
![Screenshot 2023-02-15 at 09 11 42](https://user-images.githubusercontent.com/82377035/218975509-68f8b497-feef-46e0-bc66-451d47821fd6.png)
![Screenshot 2023-02-15 at 09 19 27](https://user-images.githubusercontent.com/82377035/218975721-d9c4cb93-76d3-4732-ac60-fb76378a967c.png)
![Screenshot 2023-02-15 at 09 27 46](https://user-images.githubusercontent.com/82377035/218973357-376e82d6-6ea7-47cc-bb20-a650a83d247f.png)

We made the same change in android and no requests will be sent to "tags.tiqcdn.com" after overriding tagManagementOverrideURL and publishSettingsURL, that means we have an issue in Tealium-swift Pod

**Note**: It's a react-native application, but the Tealium part in developed in native (Kotlin and Swift).

**Comment by craigrouse** [comment]
@mharidyMMS could you please send an email to support@tealium.com so we can look into the specific configuration on your account? Please reference this issue in the email. Thank you.
