### ISSUE TITLE
[TEALIUM SWIFT BUG]: Migration from old SDK - charles tags.tiqcdn missing

### ISSUE THREAD

**Issue by salvatoreboemia** [Tealium/tealium-swift#294]
**Your Environment**
- Xcode 14.2
- Swift version 5.6
- pod 'tealium-swift', '2.9.1'

**Describe the bug**

I updated to the new SDK, but on charles I no longer see the logs:

- tags.tiqcdn
- 404 datacloud tealium

I am no longer able to view these logs via charles.

Is there something specific that needs to be activated on the server side (dashboard) or something specific on the Swift code side?

(with the old version everything works fine)

**PS: I sent "qa" as environment**

EDIT:

I also set the consent in the code to .gdpr and .consented

```
tealConfiguration.consentPolicy = .gdpr
tealiumInstance = Tealium(config: tealConfiguration)
tealiumInstance?.consentManager?.userConsentStatus = .consented
```

but in the console I still see this

<img width="428" alt="image" src="https://user-images.githubusercontent.com/20614870/224942364-8b3eba4a-1985-4250-9026-cfb7d553b862.png">

maybe that's why I don't see log in dev?

**Comment by Enricoza** [comment]
Hi @salvatoreboemia, I'll try to solve your doubts.

`tags.tiqcdn` url is used for several products and APIs. Are you using anything in particular that is not working? If it's TagManagement you need to pass the tag management module in the config's dispatchers:

```swift
import TealiumTagManagement
...
config.dispatchers = [
                Dispatchers.TagManagement
                ]
```

`404 datacloud tealium` this was moved to a new endpoint.

For the consent, instead, tealium instance gets initialized asynchronously, so if you want to use it right away you need to pass in the completion block and use it from there. For example:

```swift
tealiumInstance = Tealium(config: config) { [weak self] response in
            guard let self = self,
                  let teal = self. tealiumInstance else {
                return

            }
            teal.consentManager?.userConsentStatus = .consented
}
```

Just one last thing to note: at some point in your integration process you might want to move consent somewhere where the user can actually give consent. Setting consent for everyone indipendently does nothing different than just omitting consent.

Let me know if this solves your issues.

**Comment by salvatoreboemia** [comment]
> 

Thanks for your hint, fixed

**Comment by Enricoza** [comment]
Glad I could help. Closing for now.
