### ISSUE TITLE
Carthage scope error

### ISSUE THREAD

**Issue by ddengler** [Tealium/tealium-swift#31]
I integrated the framework using Carthage. When I try to initialize the root object with

`Tealium(config: tealConfig)`

It fails with the following error: the initializer is inaccessible due to the internal protection level. 

Makes sense as it is not marked public. Seems to have been removed in this commit:

https://github.com/Tealium/tealium-swift/commit/9dbf851b9b340e42949f5e75523f6b4653e7d2dd#diff-b8b04c2938bbe93c8c790f65fc16a539

**Comment by craigrouse** [comment]
@ddengler we are aware of this, and just about to release a fix. Please hold tight for now and I'll post back here as soon as the fix is released (should be this week).

**Comment by jalakoo** [comment]
Thanks @ddengler, we are aware of the access control issues and an update will be released before the end of the week.

**Comment by jalakoo** [comment]
@ddengler Released has been pushed to next week following some additional testing.

**Comment by ddengler** [comment]
@jalakoo please let me know the status here. We are pretty short before a release and I will need to switch to the "old" lib without carthage support unless this is released today / monday the latest.

**Comment by craigrouse** [comment]
@ddengler we just released Swift 1.3.2. It's available for Carthage, or alternatively, you can use the source version. The Carthage build will show a slightly extended build number - "1.3.2.9". Please let us know if you have any questions or issues.

**Comment by craigrouse** [comment]
@ddengler this was fixed with the 1.3.2 release, so I'm closing this issue. Please let me know if you have any further problems.
