### ISSUE TITLE
[TEALIUM SWIFT BUG]: Cannot build on Simulator `arm64-apple-ios-simulator` missing

### ISSUE THREAD

**Issue by mostafaberg** [Tealium/tealium-swift#310]
**Your Environment**
iOS Version(s): 16.4
Xcode version: 4.3.1 (14E300c)
Swift version: 5
Tealium Swift library version [e.g. 1.6.7]: 2.10.1
Dependency manager [None/Carthage/CocoaPods]: cocoaPods
Dependency manager version: 1.12.1

**Describe the bug**
Building on an M1 machine produces the following error:

> Could not find module 'TealiumSwift' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator,

**Does a workaround exist?**
Building on non-M1 machines works

**To Reproduce**
Build a project that has the pods

```ruby
pod 'tealium-swift/Core', '~> 2.10.1'
pod 'tealium-swift/Collect', '~> 2.10.1'
pod 'tealium-swift/Lifecycle', '~> 2.10.1'
```

**Expected behavior**
Builds would work properly on simulators on M1 Macs.

**Comment by craigrouse** [comment]
This is strange @mostafaberg - it certainly should work. Please bear with us while we investigate, and we'll get back to you ASAP.

**Comment by mostafaberg** [comment]
> This is strange @mostafaberg - it certainly should work. Please bear with us while we investigate, and we'll get back to you ASAP.

Thanks a lot ! let me know if I can help with any more details :)

Note: this only happens on simulator builds, building straight on device works fine of course.

**Comment by craigrouse** [comment]
@mostafaberg I have just built successfully on my M1 mac for the simulator. Here are the steps I followed:

* Create new Xcode project
* `pod init`
* Add
```
pod 'tealium-swift/Core', '~> 2.10.1'
pod 'tealium-swift/Collect', '~> 2.10.1'
pod 'tealium-swift/Lifecycle', '~> 2.10.1'
```
* pod install --repo-update
* Import `TealiumSwift` and initialize Tealium
* Run on simulator

There are no restrictions in our podspec to prevent it from working on M1 Macs, and my test proves that it works, so I assume there must be an issue in your project. Can you try running `pod update`?

**Comment by mostafaberg** [comment]
That's interesting, let me do research here then and get back to you soon :)

**Comment by mostafaberg** [comment]
You're correct, this seems to be something on our project then, I built a new clean project and followed your repro ant it built okay I'll close this ticket for now and if I discover something else I'll just reopen a new one !

thanks for your help ! 🙇

**Comment by mostafaberg** [comment]
✅  Root cause found, I'll post it here for future reference in case someone else stumbles upon this ticket.

Project setup is in React Native 0.72.

🐛 Reason: React had a project structure that included the following settings that caused troubles, here is the settings that did work in `project .pbxproj`.

- SDKROOT = auto;
- SUPPORTED_PLATFORMS = "iphonesimulator iphoneos";
- ALLOW_TARGET_PLATFORM_SPECIALIZATION = YES;
- SUPPORTS_MACCATALYST = YES;

additionally, I removed exclude architecture workarounds (that was irrelevant, but would be nice to remove if they're not actively needed for some specific reason.)
