### ISSUE TITLE
[TEALIUM EVOLUTION] : Adding device models

### ISSUE THREAD

**Issue by rabehssera** [Tealium/tealium-swift#312]
Hi

With the new devices being sold in the coming days, could you please update your device list here with the new models :
https://github.com/Tealium/tealium-swift/blob/main/tealium/core/devicedata/device-names.json

Plus, can you add a better tracking for Mac computers for Catalyst apps, by adding the different Macs to the list. (Here's the list I compiled to start with)
[mac_list.txt](https://github.com/Tealium/tealium-swift/files/12660008/mac_list.txt)

**Comment by Enricoza** [comment]
Hi @rabehssera thank you for the report and the mac's list. 
We will try to add the new device models to the list in the next release.
