### ISSUE TITLE
[TEALIUM SWIFT BUG]: Apple Silicon Simulator not suppported

### ISSUE THREAD

**Issue by LuisOskar** [Tealium/tealium-swift#313]
**Your Environment**
*Fill out as appropriate.*
iOS Version(s) [e.g. 12.1]: 16.4
Xcode version [Xcode> About Xcode e.g. 10.1 (10B61)]: 15
Swift version [e.g. 4.2]:  5.9
Tealium Swift library version [e.g. 1.6.7]: 2.10.1
Dependency manager [None/Carthage/CocoaPods]: SPM
Dependency manager version:  -

**Describe the bug**

When building in Xcode 15 on an Apple Silicon Mac for the simulator the following message appears:

> Build failed because TealiumCore.swiftmodule is missing a required architecture. Would you like to build for Rosetta instead?

**Does a workaround exist?**

Yes, building with Rosetta

**To Reproduce**
Steps to reproduce the behavior. If applicable, please attach sample code showing how to reproduce the bug. Remember to keep your Tealium account details private, and only post generic code. Additional code or crash logs may be shared with us privately on support@tealium.com.
1. Build for the simulator on an apple silicon mac

...

**Expected behavior**

To be able to use the non-rosetta version of the simulator since there is a performance impact.

**Screenshots**

**Additional context**

**Comment by Enricoza** [comment]
Hi @LuisOskar, thank you for opening this. 
I'm not able to test the exact environment you have at the moment but I had a couple questions:
1. Did you add tealium-swift directly as a dependency or was it embedded in another framework?
2. Did you try with a new, empty, Xcode project and just import `tealium-swift 2.10.1` as package dependency there and see if it works?
3. Was it updating to Xcode 15 that broke M1 support for you? Can you try again on Xcode 14, if you haven't already?

**Comment by Enricoza** [comment]
Hi again @LuisOskar, 
We've managed to test on XCode 15 and an M1 mac and it works for us without Rosetta.
Have you been able to solve your issues or can you add more info to help us investigate?

**Comment by LuisOskar** [comment]
Sorry I haven’t had the time to test further since the workaround exists.
I’ll test it and report back soon.
