### ISSUE TITLE
Incorrect TagManagementModule Payloads

### ISSUE THREAD

**Issue by KVTaniguchi** [Tealium/tealium-swift#32]
present as of in 1.3.1 -

If a client attempts to upload a payload that is not in [String: String] format such as `track(title: "title", data: ["key": ["valueInArray"]], completion: nil)` , the payload is incorrectly formatted to "title": "["valueInArray"]" NOT "title": ["valueInArray"]

The responsible methods are:
`class func jsonEncode(sanitizedDictionary:[String:String]) -> String?`
in line 453 of the `TealiumTagManagementModule` file.

`class func sanitized(dictionary:[String:Any]) -> [String:String]`
in line: 466 of the `TealiumTagManagementModule` file.

Options for fixing
1. modify and bypass
- change `class func jsonEncode(sanitizedDictionary:[String:String]) -> String?` to ``class func jsonEncode(sanitizedDictionary:[String:Any]) -> String?``
- bypass sanitizing the `appendedData` in line 360
2. 
- update `class func sanitized(dictionary:[String:Any]) -> [String:String]` to return [String: Any]
- update the sanitized class function above to correctly handle multiple data types, possibly only removing `nil` values and replacing them with a default value instead of stringifying as a last resort.

Finally, rigorous tests should be written first to ensure data handling.

**Comment by jalakoo** [comment]
Thank you @KVTaniguchi, these changes are already in the 1.3.2 branch that is undergoing final testing next week.

**Comment by craigrouse** [comment]
@KVTaniguchi we just released the 1.3.2 update to the Swift library. This should resolve your issues. Please let us know if you need further assistance.

**Comment by craigrouse** [comment]
@KVTaniguchi I am going to close this for now. If you have any further issues, feel free to re-open with your comments.
