### ISSUE TITLE
XCFrameworks are not signed

### ISSUE THREAD

**Issue by AlbGarciam** [Tealium/tealium-swift#326]
iOS Version(s): 17
Xcode version:  15.2
Swift version: 5.9.2
Tealium Swift library version: 2.12.1 
Dependency manager: None
Dependency manager version: 

**Describe the bug**
As a requisite of Apple all xcframeworks containing a privacy manifest have to be signed with the issuer certificate. Your current solution is not providing signed xcframeworks

**Expected behavior**
XCFrameworks should be signed

**Screenshots**

<img width="256" alt="image" src="https://github.com/Tealium/tealium-swift/assets/45308839/70590e70-c9d5-4183-ba0c-556d7fa5c401">

**Comment by craigrouse** [comment]
@AlbGarciam please bear with us while we look into this. We'll aim to get it resolved quickly.

**Comment by Enricoza** [comment]
Hi @AlbGarciam, thank you for pointing this out. 
I've just updated the framework in the latest release with the codesigned ones. Let me know if everything is alright now with the new frameworks.

**Comment by AlbGarciam** [comment]
Seems to be fixed now. Adding the evidence :) 

<img width="246" alt="image" src="https://github.com/Tealium/tealium-swift/assets/45308839/3f298ad8-4799-4b73-a46a-89ba8b1d6a14">

Thanks
