### ISSUE TITLE
Invalid API reason declaration

### ISSUE THREAD

**Issue by AlbGarciam** [Tealium/tealium-swift#329]
**Your Environment**
*Fill out as appropriate.*
iOS Version(s): 13.0
Xcode version: 15.3 (15E204a)
Swift version: 5.10
Tealium Swift library version: 2.12.1 
Dependency manager: None

**Describe the bug**
When publishing the final application Apple warns about an invalid configuration of the XCPrivacy manifest of Tealium. The error is the following one:

```
ITMS-91055: Invalid API reason declaration - The PrivacyInfo.xcprivacy for the “Frameworks/TealiumCore.framework/TealiumCore”
file contains “CA92.1” as the value for a NSPrivacyAccessedAPITypeReasons key instead of a valid reason code for using an API in
the NSPrivacyAccessedAPICategoryDiskSpace category. While no action is required at this time, starting May 1, 2024, when you
upload a new app or app update, values for NSPrivacyAccessedAPITypeReasons keys in your app’s privacy manifest must be valid
reason codes for the corresponding API category. For more details about this policy, including a list of required reason APIs and
approved reasons for usage
```

**Does a workaround exist?**
No

**To Reproduce**
Include Tealium core as part of your app and publish to the market.

**Expected behavior**
No error is raised

**Comment by Enricoza** [comment]
Hi @AlbGarciam, thanks for opening this. They are right we accidentally copied the wrong value, will make a release shortly with the updated manifest.

**Comment by Enricoza** [comment]
Hi @AlbGarciam, thank you again for opening this. We just made a release with the updated Privacy Manifests. Let us know if you have any other issues!
