### ISSUE TITLE
[TEALIUM SWIFT BUG]: Building on macOS fails due to incompatible macOS min versions

### ISSUE THREAD

**Issue by p4checo** [Tealium/tealium-swift#333]
**Your Environment**
macOS Version(s) [e.g. 12.1]: 14.5 (23F79)
Xcode version [Xcode> About Xcode e.g. 10.1 (10B61)]: 15.4 (15F31d)
Swift version [e.g. 4.2]: 5.10 (5.10.0.13)
Tealium Swift library version [e.g. 1.6.7]:  2.13.0
Dependency manager [None/Carthage/CocoaPods]: SPM
Dependency manager version: 5.10

**Describe the bug**
When building Tealium via SPM on the console for macOS, it's failing due to incompatible min macOS versions:

```
error: the library 'TealiumContentsquare' requires macos 10.13, but depends on the product 'TealiumCore' which requires macos 10.14; consider changing the library 'TealiumContentsquare' to require macos 10.14 or later, or the product 'TealiumCore' to require macos 10.13 or earlier.
error: the library 'TealiumContentsquare' requires macos 10.13, but depends on the product 'TealiumRemoteCommands' which requires macos 10.14; consider changing the library 'TealiumContentsquare' to require macos 10.14 or later, or the product 'TealiumRemoteCommands' to require macos 10.13 or earlier.
error: the library 'TealiumFirebase' requires macos 10.13, but depends on the product 'TealiumCore' which requires macos 10.14; consider changing the library 'TealiumFirebase' to require macos 10.14 or later, or the product 'TealiumCore' to require macos 10.13 or earlier.
error: the library 'TealiumFirebase' requires macos 10.13, but depends on the product 'TealiumRemoteCommands' which requires macos 10.14; consider changing the library 'TealiumFirebase' to require macos 10.14 or later, or the product 'TealiumRemoteCommands' to require macos 10.13 or earlier.
```

**Does a workaround exist?**
No. the only solution was to remove any Tealium dependencies from my Package.swift

**To Reproduce**
Steps to reproduce the behavior. If applicable, please attach sample code showing how to reproduce the bug. Remember to keep your Tealium account details private, and only post generic code. Additional code or crash logs may be shared with us privately on support@tealium.com.

1. Set up Tealium via SPM with `macOS` platform and the following dependencies:
```
    platforms: [
        .macOS(.v12),
    ],
    // ...
    dependencies: [
        .package(url: "https://github.com/tealium/tealium-swift", from: "2.13.0"),
        .package(url: "https://github.com/Tealium/tealium-ios-firebase-remote-command", from: "3.2.0"),
        .package(url: "https://github.com/Tealium/tealium-ios-contentsquare-remote-command", from: "2.3.0"),
    ]
```

2.  Try to build the project via SPM in terminal, or in Xcode
`swift build`

**Expected behavior**
Project builds for macOS.

Thanks!

**Comment by Enricoza** [comment]
Hi @p4checo, thank you for opening this. 
Let me see if I understand what you are trying to achieve:
Are you trying to build another Swift Package that uses Tealium as a Dependency? And will it be used on a macOS App?

If that is correct I'm afraid that we are not currently supporting macOS for remote commands. 
If you need that, you can raise a feature request ticket at [support.tealiumiq.com](https://support.tealiumiq.com) and we can go from there. 

That being said, I don't think it will be possible to embed `TealiumContentsquare` in a macOS SDK/App as the underlying `ContentSquare` package is also only supported on iOS as far as I know.
Firebase, instead, seems to be supported both on iOS and macOS.

Let me know if I can help with anything else.

**Comment by p4checo** [comment]
Hi @Enricoza 👋🏼 
Thanks for such a quick reply!

We're actually integrating Tealium on an iOS app via SPM, however we are also using some SPM plugins (SwiftFormat / SwiftGen) that currently require execution from the command line, due to Xcode/SPM sandboxing limitations. That forces us to having to run them via SPM on the package root which treats the package as a macOS target. e.g.:

- SwiftFormat: `swift package plugin --allow-writing-to-package-directory swiftformat --swiftversion 5 --lint --lenient`
- SwiftGen:  `swift package --allow-writing-to-package-directory generate-code-for-resources`

As you mention both `TealiumContentsquare` and `TealiumFirebase` are not configured to be built for macOS on their `Package.swift` manifests, so they're fallback to macOS `10.13` by default. However `TealiumSwift` specifies support for `.macOS(.v10_14)`, which is causing this issue. Any chance we can make the versions compatible?

Alternatively, we will need to conditionally remove `TealiumContentsquare` and `TealiumFirebase` from the Package when building for macOS, e.g. via a compiler directive.

Thanks! 🙏🏼
