### ISSUE TITLE
Cannot able to install the library via carthage

### ISSUE THREAD

**Issue by kmuralidharan91** [Tealium/tealium-swift#4]
Dependency "tealium-swift" has no shared framework schemes for any of the platforms: iOS

**Comment by kmuralidharan91** [comment]
in my cartfile:
github "Tealium/tealium-swift" "master"

**Comment by jalakoo** [comment]
@kmuralidharan91 We'll be testing Carthage support in version 1.1 currently in development.

**Comment by jalakoo** [comment]
@kmuralidharan91 Carthage support tested for released 1.1 update.  Please let us know if you encounter any problems.
