### ISSUE TITLE
Dependency Analysis Warnings

### ISSUE THREAD

**Issue by CRoig** [Tealium/tealium-swift#46]
Hi Team,

Can you please fix following analysis warnings on your last release?

```
warning: no rule to process file '/Users/***/Documents/***/Pods/tealium-swift/tealium/scripts/run-swiftlint-tests.sh' of type text.script.sh for architecture arm64
warning: no rule to process file '/Users/***/Documents/***/Pods/tealium-swift/tealium/scripts/run-swiftlint.sh' of type text.script.sh for architecture arm64
```

Thanks

**Comment by craigrouse** [comment]
@CRoig looks like you're using CocoaPods to import the framework into your project. Is that correct?

**Comment by craigrouse** [comment]
@CRoig I just pushed a new pod to CocoaPods (1.6.1). The only change is that these files are excluded. Can you please try again and let me know how you get on?
