### ISSUE TITLE
No tracking since 1.6

### ISSUE THREAD

**Issue by pablogthuillier** [Tealium/tealium-swift#48]
I don't know if is only me, but since 1.6 I'm not able to see any track in Tealium portal. I can still see the tracking from older versions (until 1.5.2), but not from 1.6 on.

Is someone facing same problem? I didn't change any API call, just updated pod from 1.5.2 to 1.6.1.

Thanks.

**Comment by craigrouse** [comment]
Hi @pablogthuillier. 1.6 introduced Consent Manager for GDPR compliance. If you haven't set the user's consent options, all tracking calls will be blocked until you do this. Alternatively, you can disable the consent manager. Please see here for documentation: https://community.tealiumiq.com/t5/Tealium-for-Swift/Swift-Module-Consent-Manager/ta-p/24572

**Comment by pablogthuillier** [comment]
Right, I missed that part. Everything solved. Thank you! 👌🏼

**Comment by craigrouse** [comment]
Good news @pablogthuillier. Let us know if you need anything else :-)
