### ISSUE TITLE
Carthage builds automatically create Crash frameworks

### ISSUE THREAD

**Issue by NickHughesDSW** [Tealium/tealium-swift#50]
When doing Carthage builds, TealiumCrash.framework and TealiumCrashReporteriOS.framework are created as dependencies.  Cocoapods does not do this, feel this is an issue.

**Comment by tyler8691** [comment]
Is there any supported way of using the tealium-swift framework without using the crash reporting functionality, while also using carthage?

Currently plcrashreporter does not compile with Xcode 10, so even though we don't use the crash frameworks our carthage build is blocked. Removing the requirement to checkout and build the Tealium crash reporter seems to make the most sense here.

**Comment by jonwong-tealium** [comment]
@NickHughesDSW @tyler8691 We will be removing the Carthage dependency from `master`. Will update again when it's completed. Thanks.

**Comment by craigrouse** [comment]
@NickHughesDSW @tyler8691 we have just released a fix for this. Crash reporter is now removed from the Carthage build. Please test and let us know how you get on.

**Comment by craigrouse** [comment]
Fix released. I'm now closing this issue, but please feel free to reopen if there are any further problems.
