### ISSUE TITLE
Carthage build includes Swift Libs

### ISSUE THREAD

**Issue by NickHughesDSW** [Tealium/tealium-swift#52]
The generated Tealium.framework includes a subfolder 'Frameworks' that includes the swift standard libraries.  When uploading an app to the App Store, Apple rejects the app because Frameworks are not to be included in Frameworks.

**Comment by craigrouse** [comment]
@NickHughesDSW we are looking into this. We'll respond ASAP.

**Comment by craigrouse** [comment]
@NickHughesDSW fix identified and on its way very soon. Stay tuned...

**Comment by craigrouse** [comment]
@NickHughesDSW the fix is released now. Make sure you don't have any cached Carthage builds, as we've retained the version number (1.6.2), since this was just a change to the Xcode project's targets. Let us know if this solves the problem for you.

**Comment by craigrouse** [comment]
Fix released. Closing issue.
