### ISSUE TITLE
Tealium.Framework includes IDFA Modules and Autotracking Modules

### ISSUE THREAD

**Issue by NickHughesDSW** [Tealium/tealium-swift#53]
The implementation notes state that IDFA is ok for Apple submission by selection attribution.  New App Store guidelines do not allow this and there is no way to submit without manually removing the attribution module from the .Framework.  

Also-
By your own documentation, autotracking is not recommended, yet is included in the framework.

Alternatively, you could have separate frameworks that include each of this.

FYI.  We are using Carthage builds.

**Comment by craigrouse** [comment]
@NickHughesDSW we are working on properly decoupling the optional components so that you don't need to have the bits you don't want. You should disable unwanted modules using the module list passed to the config object, which will deactivate the optional functionality (idfa, autotracking). 

Could you please point me to the new app store guidelines stating that IDFA is not allowed for attribution purposes?

**Comment by craigrouse** [comment]
@NickHughesDSW Are you sure this option has gone? See: http://www.brianjcoleman.com/wp-content/uploads/2014/07/IDFA_Page2-1.jpg

I'd be amazed if Apple has removed this, as it's the main way to do attribution on iOS, and it would instantly render attribution frameworks useless if they disallowed IDFA usage for attribution. "Attribute to a previously served ad" and "Attribute an action..." should both be checked. Keen to make sure we have the right info here - we certainly don't want to create any barriers to app submission.

**Comment by NickHughesDSW** [comment]
I will grab an updated screenshot tomorrow.  Our app is under review so I can't upload the old version right now.

**Comment by NickHughesDSW** [comment]
@craigrouse we ended up forking and removing the attribution module directly.  So I was not able to get the screenshot.  But I would think you could easily recreate by attempting to submit an app for review with your standard .framework included.

**Comment by craigrouse** [comment]
@NickHughesDSW Tealium Swift 1.6.5 is out, and all modules are now available separately as optional components (either through CocoaPods or Carthage). Please see here for full release notes, and updated install docs: https://community.tealiumiq.com/t5/Tealium-for-Swift/Swift-Library-Release-Notes/ta-p/20568
