### ISSUE TITLE
String values on in Collect Payload?

### ISSUE THREAD

**Issue by NickHughesDSW** [Tealium/tealium-swift#66]
Noticed an issue with our latest release of our [Int] being stringafied and located this being done here.

`    /**
     Clears dictionary of any value types not supported by collect
     */
    class func sanitized(dictionary: [String: Any]) -> [String: Any] {
        var clean = [String: Any]()

        for (key, value) in dictionary {

            if value is String ||
                value is [String] {

                clean[key] = value

            } else {

                let stringified = "\(value)"

                clean[key] = stringified
            }
        }

        return clean
    }`

Just need to verify that only String and [String] are valid types for Collect payloads?  In the previous tealium-ios project, we could send [Int].

Thanks.

**Comment by craigrouse** [comment]
@NickHughesDSW It's generally best to stick with String and [String] for most Tealium products. The fact that we are stringifying will not affect the data being received in Tealium UDH. The specified type of the property (e.g. Metric/Number) will determine how the value is interpreted.

**Comment by NickHughesDSW** [comment]
Sending an [Int] array results in this payload:

`product_units=%5B1%5D`

Which is:

` "product_units": "[1]"`

are you saying this will be translated correctly into our downstream analytics provider?  Adobe in this case.

**Comment by craigrouse** [comment]
@NickHughesDSW as long as it is correctly configured in the UDH, then yes. You would need to have an attribute configured as an "Array of numbers" in UDH, which is then mapped in the Adobe connector. UDH will translate the encoded array value into a real array of numbers before it is sent on to the designated parameter in the Adobe connector. The support team can help further to get this set up if you have any trouble (support@tealium.com). I hope this answers your question sufficiently. We are moving to a different request type soon, which will change the UDH hit from a GET to a POST, with a much easier-to-read payload (a standard JSON post request).

**Comment by craigrouse** [comment]
@NickHughesDSW Tealium Swift 1.6.5 addresses this issue, and "Collect" requests are now sent via POST, and nested objects and arrays are not sanitized. Please try it out and let us know how you get on.
