### ISSUE TITLE
1.6.5 failed to compile

### ISSUE THREAD

**Issue by alexliubj** [Tealium/tealium-swift#71]
In TealiumdeviceData.swift
Can not find UIApplication.shared at line 339 and 342, but if I revert to 1.6.4 it works.

**Comment by craigrouse** [comment]
@alexliubj how did you install? CocoaPods, Carthage, or manual install?

**Comment by craigrouse** [comment]
If CocoaPods, please try `pod cache clean --all`, then recompile

**Comment by alexliubj** [comment]
Yes I was using cocoapods 
Like Pod tealium-swift , which means the latest version. It works before today.

**Comment by craigrouse** [comment]
@alexliubj please try cleaning CocoaPods cache as stated above. This may resolve the problem. Which Swift version are you using in your project? Are you using Xcode 10?

**Comment by alexliubj** [comment]
Still have the same issue 
Xcode 10.1 build10b61
Pod —version 1.5.3

**Comment by craigrouse** [comment]
Which Swift version are you using?

**Comment by alexliubj** [comment]
4.2

**Comment by craigrouse** [comment]
Is this for an iOS target, or another platform? The code block is wrapped in `#if os(iOS)`, so should only be compiled for iOS targets. I can't reproduce the problem with a fresh Xcode project on my end, same Xcode version, latest pod.

**Comment by craigrouse** [comment]
@alexliubj can you open up Xcode, look at your `Pods` workspace, `Pods > tealium-swift > TealiumFull` (assuming you are using the full pod), then look at `TealiumDeviceData.swift`. Line 334 should have the `#if os(iOS)` check. If that's not there, then you still have an outdated/cached pod.

**Comment by alexliubj** [comment]
Yes when I was compiling it, target was set to iOS: 
Let me double check if there’s anything else was wrong.

I also checked line 334, there is a #if iOS and I also compared with 1.6.4, application.shared doesn’t exist.

**Comment by craigrouse** [comment]
@alexliubj this is a new bit of code for 1.6.5, so you wouldn't see it in 1.6.4.

**Comment by alexliubj** [comment]
Yes when I was compiling it, target was set to iOS: 
Let me double check if there’s anything else was wrong.

I also checked line 334, there is a #if iOS and I also compared with 1.6.4, application.shared doesn’t exist.

**Comment by alexliubj** [comment]
We can just live with 1.6.4 at this moment, it works fine to us.

**Comment by craigrouse** [comment]
OK @alexliubj; no problem. If you get the chance, it would be great if you can fire up a fresh Xcode project and reinstall the 1.6.5 pod, and just see if you get the same issue. I'd like to understand if this issue is specific to your project.

**Comment by alexliubj** [comment]
I think it was because we were using inside Siri stuff like intent and SiriUI.

**Comment by craigrouse** [comment]
@alexliubj OK - makes sense. You could consider using 1.6.5 and omitting the DeviceData module from your SiriKit extension target. Instructions here: https://community.tealiumiq.com/t5/Tealium-for-Swift/Swift-Install-with-CocoaPods/ta-p/20020.

I'll close this issue for now, as I don't believe it's a bug as such, but please do get in touch if you need further assistance.

**Comment by craigrouse** [comment]
@alexliubj we just pushed an update that **should** enable you to use the latest version if you wish. The "unsafe" API call has been wrapped to make it suitable for use in app extensions. Please give it a try and let us know if it works for you.

**Comment by alexliubj** [comment]
Hi Craig, forgot to have an update.
We use sub pods instead of one entire pod at the end and there wasn't any issue came up.

```
pod 'tealium-swift/Core'
    pod 'tealium-swift/TealiumConsentManager'
    pod 'tealium-swift/TealiumConnectivity'
    pod 'tealium-swift/TealiumDefaultsStorage'
    pod 'tealium-swift/TealiumDelegate'
    pod 'tealium-swift/TealiumDeviceData'
    pod 'tealium-swift/TealiumDispatchQueue'
    pod 'tealium-swift/TealiumLogger'
    pod 'tealium-swift/TealiumTagManagement'
```

**Comment by craigrouse** [comment]
Thanks for the update @alexliubj.
