### ISSUE TITLE
RemoteCommands being enabled more than once

### ISSUE THREAD

**Issue by Enricoza** [Tealium/tealium-swift#74]
Hi, 
I’m experiencing some issues. I first tested on 1.6.3 (which I’m currently using) and then run my tests on 1.6.6 which had some changes. 

Version 1.6.3: The completion of the init (Tealium.init) is called more than once. TagManagement and remoteCommands modules are enabled over and over again (causing also the loss of all remote commands previously inserted). 
Version 1.6.6 : The completion of the init is called only once (apparently solving 1.6.3 issue) but it’s too soon (still can’t add remoteCommands on that completion).  The problem with modules being re-enabled over and over again remains the same.

From my understanding the defer mechanism added in the new init (1.6.6) was an attempt to solve the 1.6.3 first issue (correct me if I’m wrong) but, from my prospective, seems to be gone in the wrong direction.
Now the completion is called only once (apparently solving one of 1.6.3 issue) but only after the sync methods, which is not very useful since we could simply call (what we would call on the completion) on the next line of code having (virtually) the same results. The problem arises when one of the modules enables asynchronously (tagManagement) which in turn causes the completion to be called before tagManagement and remoteCommands are enabled.
Since the init on 1.6.3 was called on last module enabled (which seems reasonable), solving second issue (which still persists) would’ve solved the first too, and maybe that was the right path to follow.

I had prepared a fix for 1.6.3 but, since your logic for that init has completely changed, I can’t really tell if it would fit your needs. (I’m still assuming your changes were made to fix the first issue I mentioned on 1.6.3… but I could be wrong and maybe there’s something else that I’m missing).

Anyway I’ll explain my thoughts about the matter and than hopefully you can use them to fix everything.

The second issue was due to the fact that tagManagement’s completion of the `enable` method was called more than once on `webViewDidFinishLoad(_:)`.
This way, every time the webview finished loading whatever page it reported it was enabled again, causing re-enabling of remoteCommands (which is next module down the list of modules) and then the completion of the init of Tealium SDK (on 1.6.3).
If you, instead, after the first call of that completion, set that completion to nil, it avoids re enabling everything else on every subsequent `webViewDidFinishLoad(_:)`, solving the second issue on the spot.

Instead, for the first issue (the completion called too soon) I would suggest rolling back to version 1.6.3 handling of the completion (call it after last enable) that, alongside with the other fix should solve all the problems.

I hope that my investigation can be useful. If you need any more clarification I’m here to help.
Thank you for your time

Enrico Zannini

**Comment by craigrouse** [comment]
@Enricoza for the remote commands issue, can you please try adding your remote commands to the TealiumConfig object, introduced in 1.6.5? https://community.tealiumiq.com/t5/Tealium-for-Swift/Swift-Class-TealiumConfig/ta-p/17095#toc-hId--1738150110

This should solve the problem of the remote commands not being called.

I'm looking into the other issues you've raised and will get back to you ASAP.

**Comment by Enricoza** [comment]
@craigrouse using the method you suggested works better (but not quite best), since re-enabling remoteCommands takes back all the commands from that config every time. (again this happens on every track event... so it's very much often).

Furthermore I see this in the documentation you linked:

> // run prior to Tealium initialization

does that mean that using this method I can no longer add them afterwards?

**Comment by craigrouse** [comment]
@Enricoza You can add afterwards using the original Tealium API method, but you need to make sure that tealium?.remotecommands() returns a valid instance, and not nil. 

I'm just looking into the issue now in more detail. Will come back to you shortly.

**Comment by Enricoza** [comment]
@craigrouse yes sure, but still I don't have an event from which I can be sure I can add those.
I mean an event that can tell me: from now on remote.commands() should not return nil because its module is enabled (I mean that's what old init's completion did for me, even if it was repeated more than once)

regarding the other issue I'm waiting for you

again thank you for your effort.

**Comment by Enricoza** [comment]
@craigrouse while you go on with your investigation I'm also looking deeper in this matter.
I discovered another side effect, due to this same issue, that's more concerning.

Everytime that remoteCommands module is enabled, it calls `enableNotifications`.
So, when that notification is finally posted (and actually every time it's posted!), the `trigger` method is called multiple times (once per each enable!).

So, for example, after 10 `trackView` (each of whom in turn cause a re-enable) we get something like 12 subsequent calls of `trigger`, all on main thread, for each one of the remoteCommands triggered. (and this number goes up indefinitely)

This is probably solved just by solving the main issue here, but I wanted to warn you about this too because maybe this side effect moves the fix up in your priorities list.

**Comment by craigrouse** [comment]
Thanks @Enricoza. Yes, this issue is also solved by solving the main issue, as you said. I'm currently testing the fixes to ensure there are no unintended side effects. Hoping to release very soon.

**Comment by Enricoza** [comment]
Hi @craigrouse,
I'm writing here to ask you if you're close enough to the end of testing for this fix.

Since in the next days we are going to face a big release that largely makes use of remote commands, I wanted to ask you if you have a schedule set for the release and, if that's still far from now, if I could get access to a preview of that release to maybe test it for our needs.

Thank you

**Comment by craigrouse** [comment]
@enricoza the code is up on branch 1.6.7, and I will be preparing the release this morning. Will let you know when it's released.

**Comment by craigrouse** [comment]
@Enricoza the release is now published. Please let me know if this resolves your issues.

**Comment by Enricoza** [comment]
thank you @craigrouse, I've been testing the branch for a while and it seems to work fine, I'll let you know if something doesn't add up.

Anyway I assume I can now call `add` directly on TealiumRemoteCommand after `enableCompletion` is called, can't I?

Maybe it's worth noting it somewhere since in 1.6.5 change log you wrote that the configuration method should've been used instead
