### ISSUE TITLE
LifecycleModule not working in some cases

### ISSUE THREAD

**Issue by Enricoza** [Tealium/tealium-swift#75]
Hi,
I’m experiencing an issue with the `LifecycleModule`.

The problem is this: If the Tealium SDK is not initialized on the main Thread (maybe on another queue like this: `DispatchQueue.global().async{ ... }` or simply on the queue of the completion of a URLSession) the LifecycleModule doesn’t actually track the 3 events it should track.

The issue seems to be related to the dispatch queue created inside the `enable` method of the `LifecycleModule`.
It is created this way:
`_dispatchQueue = OperationQueue.current?.underlyingQueue`
And in the cases specified above, `underlyingQueue` returns nil.

I assume your intent was to dispatch all the `process` calls on the queue on which the user initialized the Tealium SDK (correct me if I’m wrong).
Assuming that the `enable` method is always called on that same thread (which I can’t really tell for sure but I think you could know better), than that line of code would be fine only on main thread and on OperationQueues with an underlyingQueue associated with it. 
If you want to keep it working like that in those cases, than it’s fine, but for those who don’t want it to be dispatched on main thread nor an OperationQueue with underlyingQueue, you could use a default queue, for when that method actually returns nil.

Again that comes from an assumption that you want that to happen, but other solutions are viable too:  You could accept a queue as a parameter, you could dispatch on a private queue no matter what or something else. That's just the easiest fix I could think of. 

Or maybe I’m missing something, I did something wrong or I should definitely init the Tealium SDK in some precise way. If that’s the case maybe it’s better if the official documentation underlines it clearly so it doesn't happen that someone else realizes too late that it doesn’t work. 

Thank you again
Enrico.

**Comment by craigrouse** [comment]
This is a good catch @Enricoza. I agree with your findings. I have prepared a fix for this. We will review internally, and I'll get back to you when it's released.

**Comment by craigrouse** [comment]
Fixed in 1.6.7

**Comment by Enricoza** [comment]
Yes @craigrouse, I think this issue in particular is solved in 1.6.7
Anyway I maybe see a possible bug in your disable method, even if probably it's not normally triggered.

The dispatchQueue is lazy and is created only on first processEvent.
Then, if I understand it correctly, someone could theoretically call disable (making the dispatchQueue=nil) and then re-enable the lifecycle module, and it would not work anymore. (correct me if I'm wrong)

I don't know if that may be an issue for you, I don't think it is for me.

Anyway thank you for your work!

**Comment by craigrouse** [comment]
@Enricoza that's a very good catch, but in fact, if you call "enable" again on the main Tealium instance after disabling, each module instance is recreated, meaning the dispatch queue is recreated also. Thanks for pointing this out, though.

Out of interest, are you using Carthage, CocoaPods or manual installation?

**Comment by Enricoza** [comment]
Oh okay, didn't look at the whole process. Better this way :) 

Anyway I'm using CocoaPods and precisely I'm using tealium-swift as a dependency for some pods.
