### ISSUE TITLE
Building carthage causes Finder to open the plcrashreporter directory

### ISSUE THREAD

**Issue by tyler8691** [Tealium/tealium-swift#77]
Hello,

When running a carthage build, the Carthage/Checkouts/plcrashreporter directory is always opened up by Finder. This is not a serious issue, but it is kind of annoying :)

Maybe there's a script causing this to happen?

**Comment by craigrouse** [comment]
@tyler8691 Interesting! Sorry to hear this. I personally haven't seen this before, but my colleague said he has. I'll do my best to try and figure out why this is happening. Let us know if you find any clues.

Thanks for taking the time to report this. Let us know if you have any other feedback, or if we can help in any way.

**Comment by craigrouse** [comment]
@tyler8691 Thanks again for bringing this to our attention. Thanks to kind support from the Carthage team, who identified where the issue was in our project (buried in "post build" actions in the Archive phase), this is now resolved. Please give it a try and let me know how you get on.

**Comment by tyler8691** [comment]
I confirmed this is fixed. Thanks!
