### ISSUE TITLE
UIWebView slows the main thread

### ISSUE THREAD

**Issue by Enricoza** [Tealium/tealium-swift#87]
Hi, 
I've been investigating for a while on performance issues and happened to discover an unpleasant heavy work done on the main thread by **TealiumTagManagement**.

I see you are using **UIWebView** and calling **stringByEvaluatingJavaScript**  on it.
Unfortunately this call results very slow (takes up to 20ms for what I've tested) and blocks the UI in that period of time.
I am aware that this method can't be performed asynchronously nor it can be called off of main thread, but it causes several performance issues in the current state of things.

You can imagine we are calling **Tealium.track** a lot in our apps and a 20 ms delay (every time) starts to add up. 😞

Here's just a screenshot from my time profiler that shows the heaviest line of code along with another one (**jsonStringWithDictionary**) that also could use some backgrounding:

<img width="1046" alt="Time Profiler Screen" src="https://user-images.githubusercontent.com/25841756/56425311-fc1df300-62b3-11e9-9f84-bd5d9712cf40.png">

I was wondering if you could switch your implementation to **WKWebView** that with **evaluateJavaScript** allows you to perform the same operations asynchronously and off thread.

Thanks as always for your constant support
Enrico

**Comment by jonwong-tealium** [comment]
Hi @Enricoza . We have an upcoming release that will use WKWebView in Tag Management. We're just doing some final testing. We'll let you know when it's released. Thanks!

**Comment by Enricoza** [comment]
Thank you for the really fast response!

**Comment by Enricoza** [comment]
Hi @jonwong-tealium, 
how is the testing going? Has a release date been scheduled yet?  
Maybe there's a chance I can get a beta version?

**Comment by craigrouse** [comment]
@Enricoza very nearly ready. I'll let you know as soon as it's ready.

**Comment by craigrouse** [comment]
@Enricoza Have you seen any performance improvements since updating? WKWebView unfortunately still requires use of the main thread, so I'm not sure how much improvement you'll see from this alone. We have, however, made some further optimizations which should have a positive impact on performance, and these will be in the next release.

**Comment by Enricoza** [comment]
Hi @craigrouse, 
I'm happy to inform you that I noticed a big improvement!
It is true that, also on **WkWebView**, evaluateJavascript must be used on main thread, but now it doesn't wait synchronously to perform the javascript code, so the main thread usage is really minimum. 

Unfortunately, unless the other issue with the view is not solved soon, we are gonna go out to production with the **UIWebView**, saying goodbye to all your good work and effort in optimizing this point. 😢

Anyway, any improvement in performance is really welcome, so thank you again for you work.

PS: I don't know if you've already included this in your next optimizations, but on **1.7.0** I still see the method **jsonStringWithDictionary** called on main thread while, I guess, it could be backgrounded.
From my test that's the heaviest work done on main thread in tagManagement module.

**Comment by craigrouse** [comment]
@enricoza Yes, actually I noticed that, and it led me to find that there's a lot more stuff performed on the main thread than intended. The next release moves everything to background queues where possible. Working hard to get it released ASAP.

**Comment by craigrouse** [comment]
@Enricoza you'll be pleased to know that in our latest release, as far as possible, everything is done on background threads. You can try out the new release here: https://github.com/Tealium/tealium-swift/releases/tag/1.8.0-beta1

Please have a careful read of the release notes, and feel free to contact me if you have any questions or issues.

Thanks for your patience and support.

**Comment by Enricoza** [comment]
Thank you @craigrouse, I'll test this release as soon as possible

**Comment by Enricoza** [comment]
@craigrouse I'm happy to confirm you that even in the heaviest points of my code, where it can happen to send several tracks per second,  the instruments shows me that Tealium is virtually disappeared from the main thread. So I guess this issue can be successfully closed.

Thank you again for your good work.

**Comment by craigrouse** [comment]
@Enricoza this is good news to end the week on. Thank you :-)
