### ISSUE TITLE
[TEALIUM SWIFT BUG]: Attaching to view in view hierarchy doesn't work as intended

### ISSUE THREAD

**Issue by raven** [Tealium/tealium-swift#93]
**Your Environment**
Tealium Swift library version: *1.7.0*

**Describe the bug**
Auto detecting a view that is in the view hierarchy does not work as intended. If the developer does not provide a custom view, the SDK auto-detects the currently presented view to attach to, however it assigns that back into the same variable used to denote a provided custom view, so subsequent auto-detects fail to update.

This results in the SDK attaching to a view that is in the hierarchy the first time, but then that view will likely leave the view hierarchy, resulting in poor WKWebView performance.

**Does a workaround exist?**
Yes, explicitly providing a custom view.

**To Reproduce**
1. *Do not* provide a custom view for TealiumTagManagementWKWebView to attach to (do not call `setRootView` )
1. TealiumTagManagementWKWebView does initial setup, calls out to `attachToUIView(specificView: nil)`
1. TealiumTagManagementWKWebView checks if self.view is specified, it isn't
1. TealiumTagManagementWKWebView auto detects view by grabbing the topmost presented VC, and grabs that view
1. TealiumTagManagementWKWebView assigns the auto detected view to `self.view` <-- Bug. This means subsequent auto-detection attempts will not update the view, and previously captured views may (likely) not be in the view hierarchy anymore.
1. TealiumTagManagementWKWebView attaches itself to `self.view` <-- Area for improvement, should validate that `self.view` has a `window`

**Expected behavior**
If the developer does not provide a custom view, the autodetecting should always attach itself to a view within the view hierarchy.

**Suggestion**
Instead of attempting to walk the view hierarchy and obtaining the top-most view controller, TealiumTagManagementWKWebView can just attach itself to the window directly (it is a UIView after all). 
```
if self.customView == nil {
	let currentWindow = UIApplication.shared.keyWindow
	attachTo(currentWindow)
} else {
	attachTo(customView)
}
```

**Comment by craigrouse** [comment]
@raven Thanks for taking the time to submit this.

It is very inconvenient that WKWebView requires attaching to a view. We tested quite a number of scenarios, and found that the only reliable way to cover most cases was to walk the view hierarchy. That said, it clearly didn't work as intended in your case.

We are currently working on a new release, so we'll revisit this and take note of your suggestions.

Stay tuned for updates. Thank you again, and sorry for the inconvenience.

**Comment by Enricoza** [comment]
@craigrouse I just probably encountered the same issue and found a bug in the code.

On `TealiumTagManagementWKWebView` line 100 you are using the class property `view` instead of the method parameter `withSpecificView`, which is instead unused.

I am not sure if this solves all other problems, but using the parameter seems to solve mine.

**Comment by craigrouse** [comment]
Thank you @Enricoza. We'll take a look next week.

**Comment by craigrouse** [comment]
@raven @Enricoza Thank you both for your contributions. Release 1.7.1 is now up on CocoaPods, containing this fix. A major release is on the way also, which contains a few more general optimizations and features, but we wanted to get this minor release out sooner. Please let me know how you get on with the new release. I'll leave this open until I hear from you. Thank you.
