### ISSUE TITLE
Unable to read the license file `LICENSE` for the spec `TealiumCrashReporter (1.3.4)`

### ISSUE THREAD

**Issue by stephenyao** [Tealium/tealium-swift#94]
**Your Environment**

Xcode version 10.2
Swift version 5.0
Tealium Swift library version 1.7.0
Dependency manager Cocoapods
Dependency manager version: 1.6.1

**Describe the bug**

Running pod install with tealium-swift 1.7.0 causes the following warning in the console after the install completes:

`[!] Unable to read the license file `LICENSE` for the spec `TealiumCrashReporter (1.3.4)`

**Does a workaround exist?**

It's a warning, so it doesn't stop the installation from working

**To Reproduce**

1. In podfile, add `tealium-swift` version 1.7.0 as a depdency
2. Run `pod install`
3. See the warning ``[!] Unable to read the license file `LICENSE` for the spec `TealiumCrashReporter (1.3.4)`
`
**Expected behavior**

No warning should appear after `pod install`

**Screenshots**

<img width="896" alt="Screen Shot 2019-07-16 at 4 58 29 pm" src="https://user-images.githubusercontent.com/1520125/61272650-f79da380-a7ea-11e9-9f23-b37cdb7c7012.png">

**Additional context**

This is probably because in the `TealiumCrashReporter.podspec` at https://github.com/Tealium/plcrashreporter/blob/master/TealiumCrashReporter.podspec, the source points to a zip file. But the zip file doesn't contain the license, which would cause the warning.

**Comment by craigrouse** [comment]
Thank you for submitting this @stephenyao. We'll get it updated ASAP.

**Comment by craigrouse** [comment]
@stephenyao Thanks for bringing this to our attention; it is now resolved. The Crash Reporter repo and pod has a new release (1.3.5). I just tested with the new pod, and I no longer see the warning, but I did have to clear my CocoaPods cache, and do a `pod repo update` to get the new version. Let me know if you have any further issues.

**Comment by stephenyao** [comment]
Thanks @craigrouse for fast turn around, the issue is now resolved 👍

**Comment by craigrouse** [comment]
You're welcome @stephenyao!
