### ISSUE TITLE
[TEALIUM SWIFT BUG]: Crash on TealiumAppData.swift: setNewAppData

### ISSUE THREAD

**Issue by Enricoza** [Tealium/tealium-swift#96]
**Your Environment**
Tealium Swift library version: 1.7.0 (Including lifecycle module)

**Describe the bug**
The library happen to crash on **TealiumAppData**, line 122, for a bad access error. 
It is probably due to the fact that lifecycle uses its own internal _dispatchQueue_ to track the lifecycle events, making possible the fact that two track events can be called simultaneously on two different threads. 
What I think is happening is that, due to this thread safety issue, the _setNewAppData_ is sometimes called twice and, when that happens, one of the two can crash while mutating the dictionary (which could be released by the other thread on line 121).

**Does a workaround exist?**
Not that I'm aware of.

**To Reproduce**
This is really hard to reproduce from outside of the library, nonetheless the amount of crashes are quite high.

**Expected behavior**
Track calls should be thread safe.
Otherwise a possibility to enforce a _dispatchQueue_ on lifecycle module should be added so we can share that same queue to call our _tracks_ on, from outside.

**Comment by craigrouse** [comment]
@Enricoza thank you. This is the first we've heard of this crash, but I expect it to be solved in the next release of the library, since I've done extensive work on threading and making things thread-safe. Working hard to get this out ASAP (I know you're waiting).

**Comment by craigrouse** [comment]
@Enricoza as with the other comments, this is fixed in https://github.com/Tealium/tealium-swift/releases/tag/1.8.0-beta1

Thank you.

**Comment by craigrouse** [comment]
Resolved in 1.8.0 release
